# SPDX-FileCopyrightText: 2026 Kento Konishi
# SPDX-License-Identifier: LicenseRef-All-Rights-Reserved
from __future__ import annotations

SHADOW_MAP_QUALITY_LOWEST: int = 1
SHADOW_MAP_QUALITY_LOW: int = 2
SHADOW_MAP_QUALITY_STANDARD: int = 3
SHADOW_MAP_QUALITY_HIGH: int = 4
SHADOW_MAP_QUALITY_ULTRA: int = 5

SHADOW_MAP_QUALITY_MIN: int = SHADOW_MAP_QUALITY_LOWEST
SHADOW_MAP_QUALITY_MAX: int = SHADOW_MAP_QUALITY_ULTRA
SHADOW_MAP_QUALITY_DEFAULT: int = SHADOW_MAP_QUALITY_STANDARD

SHADOW_MAP_QUALITY_ORDER: tuple[int, ...] = (SHADOW_MAP_QUALITY_LOWEST, SHADOW_MAP_QUALITY_LOW, SHADOW_MAP_QUALITY_STANDARD, SHADOW_MAP_QUALITY_HIGH, SHADOW_MAP_QUALITY_ULTRA)

SHADOW_MAP_QUALITY_LABELS: dict[int, str] = {
  SHADOW_MAP_QUALITY_LOWEST: "Lowest",
  SHADOW_MAP_QUALITY_LOW: "Low",
  SHADOW_MAP_QUALITY_STANDARD: "Standard",
  SHADOW_MAP_QUALITY_HIGH: "High",
  SHADOW_MAP_QUALITY_ULTRA: "Ultra",
}


def normalize_shadow_map_quality(value: object) -> int:
  try:
    quality = int(value)
  except (TypeError, ValueError):
    return int(SHADOW_MAP_QUALITY_DEFAULT)
  if quality < int(SHADOW_MAP_QUALITY_MIN) or quality > int(SHADOW_MAP_QUALITY_MAX):
    return int(SHADOW_MAP_QUALITY_DEFAULT)
  return int(quality)
