# SPDX-FileCopyrightText: 2026 Kento Konishi
# SPDX-License-Identifier: LicenseRef-All-Rights-Reserved
from __future__ import annotations

from dataclasses import dataclass

PROFILE_IMAGE_CANDIDATE_NAMES: tuple[str, ...] = ("profile.png", "profile.jpg", "profile.jpeg", "profile.webp", "profile.bmp")
GITHUB_IMAGE_CANDIDATE_NAMES: tuple[str, ...] = ("github.png", "github.jpg", "github.jpeg", "github.webp", "github.bmp", "github.svg")
ABOUT_GITHUB_URL = "https://github.com/5uog/Ludoxel/"

ABOUT_CREATOR_DISPLAY_NAME = "Kento Konishi"
ABOUT_CREATOR_HANDLE = "5uog"
ABOUT_CREATOR_ROLE = "Keio University student / Ludoxel creator"
ABOUT_CREATOR_AGE = "20"
ABOUT_CREATOR_GENDER = "he/him"

ABOUT_PROFILE_BIO_TEXT: str = "My academic work is directed toward future legal practice, with particular concern for victim protection, fact finding, procedural access, information management, and institutional reform. Law is the principal field of that study. Information security, software architecture, persistence design, interface construction, and verification supply an adjacent technical discipline for examining how protective systems can remain inspectable, explainable, testable, and accountable when they process human claims, evidence, access routes, stored information, and institutional decisions. Ludoxel is developed as a separate personal desktop software project, but it shares that discipline of explicit structure: state must be preserved deliberately, renderer behavior must be observable, input ownership must be controlled, and user-facing systems must be described in terms precise enough to be tested."

ABOUT_WORK_TEXT: str = "I work on Ludoxel as a PyQt6 desktop application with persistent voxel-world state, first-person and third-person camera behavior, collision, picking, block-state rendering, falling-block simulation, AI-player behavior and route planning, a separate Othello play space, platform-specific OpenGL and wgpu renderer paths, app-managed runtime persistence, bundled resources, desktop packaging, and application-facing documentation."

ABOUT_ACADEMIC_DIRECTION_TEXT: str = "My academic direction centers on legal practice, victim protection, fact finding, procedural access, information management, and institutional reform. Software-system design is relevant to that direction because protective institutions also depend on inspectable architecture, controlled state, reliable access paths, durable records, explicit procedures, and explanations that remain accurate when a system is used by a person rather than only described by its designer."

ABOUT_ETYMOLOGY_PARAGRAPHS: tuple[str, ...] = (
  "Latin 'ludus' underlies the initial element 'lud-'. Its attested semantic field extends across play, game, sport, school, and training. The stem therefore carries a broad ludic reference: play as a general class of rule-bound or exploratory activity, rather than one combat form, one genre, or one fixed rule set.",
  "'Voxel' is the modern technical contraction of 'volumetric' and 'pixel'. In technical usage, it denotes a discrete element of three-dimensional representation, commonly treated as the spatial analogue of the pixel, and therefore refers to discretized volume rather than to a merely visual style or atmospheric motif.",
  "'Ludoxel' accordingly denotes ludic activity conducted in voxel space. As the title of a sandbox desktop application, the term is operationally exact: the represented environment is voxel-constituted, while the admitted activity remains broadly ludic, extending across local manipulation, traversal, authored routes, AI observation, and a separate board-game space hosted inside the same shell.",
)


@dataclass(frozen=True)
class AboutBlock:
  kind: str
  text: str


@dataclass(frozen=True)
class AboutSection:
  title: str
  blocks: tuple[AboutBlock, ...]


def paragraph(text: str) -> AboutBlock:
  return AboutBlock(kind="paragraph", text=str(text))


def code_block(text: str) -> AboutBlock:
  return AboutBlock(kind="code", text=str(text))


ABOUT_PROJECT_OVERVIEW_SECTIONS: tuple[AboutSection, ...] = (
  AboutSection(
    title="Ludoxel v3.6",
    blocks=(
      paragraph("Ludoxel is a PyQt6 desktop application for controlled experimentation on a restricted voxel-world model, a first-person and third-person camera pipeline, persistent local application state, and platform-specific voxel renderers. The application is built as a desktop system in which world state, input ownership, simulation stepping, renderer behavior, resource loading, persistence, packaging, and legal distribution boundaries are exposed as engineering concerns rather than hidden behind a generic game label."),
      paragraph("The current application exposes two persistent modes inside a single desktop shell: My World and Play Othello (Reversi). My World is the ordinary sandbox and inspection space. Play Othello (Reversi) is a separate application mode with its own board state, match controller, AI opponent, clocks, control hotbar, settings surface, opening-book storage, animation path, and rendering path. Both modes share the same application shell, runtime preference system, persistence discipline, renderer contract boundary, modal-window policy, title-mark search path, and app-managed data root."),
      paragraph("The project is intentionally narrower than a complete Minecraft implementation. It uses selected Minecraft-like semantics as local references for survival health, fall damage, void damage, block placement, falling blocks, camera behavior, HUD expectations, and structural block families, while keeping the implemented world model restricted enough to permit direct inspection of collision, picking, block-state geometry, renderer upload, AI movement, Othello integration, desktop packaging, and persistent runtime state."),
    ),
  ),
  AboutSection(
    title="Application shell and space switching",
    blocks=(
      paragraph("The desktop shell owns the persistent transition between My World and Play Othello (Reversi). The pause menu exposes Play My World, Play Othello (Reversi), and Save & Quit. A destination action is disabled while its space is already active, and Save & Quit persists the current world, player state, active space, settings, and mode-local session data before application closure."),
      code_block("Play My World\nPlay Othello (Reversi)\nSave & Quit"),
      paragraph("Each play space persists its own player transform and session-specific state. Returning to My World restores the sandbox player, local world edits, inventory branch, AI actors, and sandbox runtime context. Returning to the Othello space restores the Othello player transform, board world, match defaults, clock state, persisted Othello state, and Othello-specific hotbar branch without treating either mode as a transient overlay over the other."),
      paragraph("The pause overlay is organized as a screen-wide two-column surface. The left half is vertically centered as a combined title-and-control column: the same Ludoxel title image search path used by the loading screen is rendered above the boxed session and space-management controls, the image is shown without a separate color plate behind it, and the logo/control stack is centered as one unit."),
      paragraph("The right half contains a vertically centered, unboxed live slim-arm player preview with skin import and reset actions placed immediately below it. The preview interaction path supplies desired view angles to the renderer API rather than defining a second cube-layout or UV implementation inside the UI. Backends that have not migrated full preview rendering degrade through the same public preview API instead of causing the settings surface to own renderer-specific body geometry."),
      paragraph("Pointer motion across the pause surface, including both columns, steers the preview head orientation whenever the left mouse button is not held. Holding the left mouse button and dragging anywhere on the pause surface rotates the preview body around the vertical axis. The head yaw remains a bounded offset from the current body heading, and pitch follows the screen-space vertical direction. When third-person camera mode and gameplay HUD rendering are both active, the preview also shows the resolved session player name above the head by reusing the same HUD panel treatment applied in the world."),
    ),
  ),
  AboutSection(
    title="My World",
    blocks=(
      paragraph("My World is the ordinary persistent sandbox space. It serves as a flat inspection environment in which the implemented block subset can be placed, broken, rendered, picked, collided against, persisted, restored, and compared across renderer paths. The space is deliberately restricted when measured against the breadth of a complete Minecraft implementation, but the implemented subset is treated as a serious simulation surface rather than a decorative mockup."),
      paragraph("Outside creative mode, the local player runs under a survival-health path with a 20-point health pool shown on the gameplay HUD. Fall damage follows Minecraft-like thresholds, and lethal damage enters the ordinary death-and-respawn flow. Falling below y = -64 applies repeated void damage on a fixed half-second cadence until health reaches zero, so the void path remains part of the ordinary health and damage system rather than a separate scripted death overlay."),
      paragraph("The current catalog includes full cubes together with slabs, stairs, fences, fence gates, and walls. Each implemented family is driven by explicit block-state logic for render boxes, collision volumes, pick volumes, structural connectivity, wall top-support, and fence-gate behavior. The same state-derived geometry is used to align visible selection, collision response, falling-block support, particle emission, and persisted restart behavior."),
      paragraph("Sand, red sand, and gravel are gravity-affected blocks. They leave the static world as transient falling bodies, descend on a Minecraft-like falling-block tick, and render continuously between ticks rather than being teleported cell-by-cell through the chunk mesh. Their landing path treats lower stairs, fences, fence gates, and walls as valid resting supports for a full falling block, while collision with a lower slab destroys the falling block and emits the same block-break particle effect used by ordinary manual block breaking."),
      paragraph("Block destruction emits short-lived terrain-fragment break particles. Spawn positions are sampled from the broken block's active render boxes rather than from a hard-coded full-cube assumption. Stochastic volume sampling prevents thin members and partial-volume blocks from producing uniform fragment rows, so slabs, fences, walls, stairs, and other partial-volume structures emit fragments from their implemented geometry."),
      paragraph("The player collision path includes depenetration for pre-existing overlaps so that block edits do not leave the camera embedded in geometry. Closed fence gates preserve the Minecraft-like case in which a player already standing inside the gate is not forcibly expelled when the gate is shut around them. Landed gravity blocks likewise preserve overlap when they settle onto the player rather than pushing the player aside. Persisted-state restoration reconstructs those overlap exemptions before the first post-load collision step, eliminating the restart case in which a player saved inside a closed fence gate was lifted onto the gate on relaunch."),
    ),
  ),
  AboutSection(
    title="Block interaction and held placement",
    blocks=(
      paragraph("The ordinary block interaction path remains active inside My World. Holding the left mouse button in creative mode repeats block breaking continuously. Holding the right mouse button repeats both block placement and fence-gate interaction continuously. The persistent default cadences are 0.30 seconds for break repetition, approximately 0.008 seconds for placement continuation, and 0.20 seconds for interaction repetition. These cadences are stored with runtime preferences and can be edited from the Game Player settings page."),
      code_block("break repetition: 0.30 s\nplacement continuation: approximately 0.008 s\ninteraction repetition: 0.20 s\ninitial held-placement dwell: 0.20 s"),
      paragraph("Continuous right-click placement is constrained to a single aligned continuation line while the button remains held. The maintained line can grow in either signed direction from the first placed block. The first right-click placement remains a single isolated action, and the held repeater arms only after an initial dwell. Once armed, the held place path resumes on the high-cadence continuation path before the player collision step of each simulation tick, removing accidental two-block bursts on ordinary single clicks without sacrificing sustained bridging cadence."),
      paragraph("When the player begins a held sequence from a directly visible horizontal side face, the sequence enters a dedicated face-chain mode whose continuation axis remains locked to the same face orientation of the frontier block. When the sequence begins from supporting ground without a qualifying visible frontier face, the placement path synthesizes the same side-face basis that would result from placing against the supporting block in the current facing direction. Grounded crouch bridging prefers that horizontal reacharound basis over accidental top-face or bottom-face hits that would redirect the action into upward or downward stacking."),
      paragraph("The start-of-sequence support-face classifier accepts any hit on the supporting block that lies on the intended side half rather than only a narrow outer-edge strip. When a supporting-block hit resolves to the top or bottom face, the classifier reconstructs the intended horizontal side from the actual top-surface hit displacement whenever one horizontal axis dominates the local corner geometry. This prevents a clearly side-committed corner aim from falling back to the raw facing direction and emitting an unwanted forward wall before the side route exists."),
      paragraph("Vertical continuation is admitted only while the held sequence is still at its first follow-up decision and only while the player remains horizontally co-located with the original two-block anchor pair formed by the first placed block and its immediately preceding support block. Live support or pick context on that same pair also counts as anchored evidence. For horizontal-face starts, the preceding support block is the immediately previous block along the maintained horizontal continuation axis. For top-face and bottom-face starts, it is the actual block clicked to produce the first upward or downward placement, and the vertical branch is accepted only when the commanded vertical sign matches that starting face orientation."),
      paragraph("When the initial right-click cannot place because the target cell is still empty in the world but temporarily occupied by the player body, the repeater still arms from that clicked face and treats the unresolved hit.place cell as the starting cell of the held route. The deferred route retries that same unresolved start cell against the originally clicked support face until the block genuinely materializes there. A successful materialization preserves the matching upward or downward continuation state rather than discarding the vertical command until a later retry."),
      paragraph("The maintained frontier advances only when the attempted target cell remains a valid world block at that exact cell after the placement decision. Failure caused by player overlap, missing support, rejected placement, or unsupported falling-block conversion leaves repeat progress unchanged. The same frontier gate applies to gravity-affected placements, preventing an unsupported falling block from being treated as the next support before it leaves the static world and terminates that held continuation after the single emitted falling block."),
      paragraph("The visible-face, support-face, and generic horizontal repeat routes consult the live movement command projected onto the maintained horizontal continuation axis. They refuse to advance the forward frontier whenever the held sequence is not actually commanding motion along that axis, leaving the first follow-up decision available to the upward or downward branch. Once a vertical branch is recognized, the repeater persists the reoriented vertical line even across a no-placement retry, preventing the next tick from falling back to the previous horizontal route merely because the player had not yet crossed the next placement threshold."),
      paragraph("The first detected world-space displacement away from the hold origin locks the entire held vertical branch to that sign. A hold that has committed upward no longer emits downward placements, and a hold that has committed downward no longer emits upward placements. Once a vertical line is committed, continuation advances only toward the next neighboring frontier cell in that locked direction from the player's signed feet-height displacement measured against the hold origin rather than from the changing view ray. If the player outpaces that immediate neighboring frontier cell by more than one block, the held path does not back-fill skipped vertical cells."),
      paragraph("Support-face continuation no longer free-runs while the view remains locked to the original supporting block face. It evaluates both the directly visible frontier face and a forward projected frontier-face intersection against the maintained bridge direction. The projected frontier path remains unavailable while the player is still grounded on the pre-advance support block and becomes available only after the player has gone airborne or transferred support onto the present frontier block, with the additional requirement that the current pick ray has already advanced onto that frontier block rather than still resolving to an older support block."),
      paragraph("When the live view becomes nearly vertical, the effective interaction pitch is clamped inside the same finite domain used by the player look state, preventing near-vertical camera shake from flipping the rendered image or inverting the horizontal intent derived by the support-face classifier. For ordinary visible side-face continuation and generic horizontal continuation, the first follow-up vertical branch also accepts an upward start from the live jump command and is available from top-face and bottom-face starts."),
      paragraph("Wall top-support updates account for the presently implemented block families above the wall. A straight wall run that would otherwise remain flat reintroduces its center post when the directly overlying block is another wall or a fence. A directly overlying full cube, fence gate, slab, or stairs block promotes supported wall arms to full-height tall segments and preserves the flat center when opposite tall supports are formed, matching the implemented Minecraft-style wall top-support distinction for the available block subset."),
    ),
  ),
  AboutSection(
    title="Inventory, special items, and AI players",
    blocks=(
      paragraph("The block inventory is opened with E, world edits persist with the sandbox space, and re-entering My World restores the previous player transform together with local world modifications. The creative inventory exposes a searchable field for block names, block identifiers, and special-item identifiers, allowing large catalog scans without manual visual paging."),
      paragraph("The creative inventory includes an AI special item. Right-clicking a valid placement cell with that item spawns one standby AI at that cell immediately rather than opening a spawn-time dialog. A standby AI remains waiting at its spawn position until the player right-clicks that specific instance, which opens an application-modal per-instance settings window built on the detached sidebar-dialog shell and main.qss styling path used by common settings surfaces."),
      code_block("Standby\nRoute Patrol\nFree Roam / PVP\nAggressive\nPeaceful\nAllow block placement\nDelete AI"),
      paragraph("The per-instance AI settings surface controls behavior mode, personality, block-placement permission, route style, route editing, and actor deletion. Route configuration temporarily switches the active hotbar to a dedicated route-edit branch whose leftmost slot contains the check item, whose second slot contains the eraser item, and whose rightmost slot contains the cancel item. While route editing is active, left-clicking ground-block top faces records route points, the eraser slot focuses and deletes points under the crosshair, and the viewport draws draft and committed routes as world-space line strips."),
      paragraph("The actor currently being edited is frozen for the duration of route editing, and any pending background route request for that actor is canceled before editing begins so that the instance does not continue stepping into damage or death while its patrol path is authored. Closing the route back onto the first point yields a continuous loop, while an open route causes the AI to traverse to the terminal point, return to the first point, and repeat."),
      paragraph("Route patrol offers Strict and Flexible routing styles. The strict form aims directly at authored patrol points. The flexible form snapshots a bounded world window around the patrol region, offloads full support-cell route planning to a dedicated background worker, accepts only complete routes that reach the presently authored patrol point, and reuses the returned support-cell path until the world changes or the next edge is proved blocked by collision, failed placement, or repeated lack of progress."),
      paragraph("The flexible planner uses the same collision-derived support semantics as the player ground detector. It prefers ordinary short step-up and auto-jump traversals before longer parkour, admits short downward drop transitions where landing support is collision-safe, resolves authored patrol points onto the nearest reachable standable support within a wider local neighborhood, and periodically retries failed patrol targets even when the static world has not changed. This prevents a locally failed jump or descent from freezing the actor forever on the same world revision."),
      paragraph("While no fresh full route is available, the runtime keeps a short-lived set of recently avoided support cells and applies a bounded local recovery search that prefers genuinely different nearby supports over immediately repeating the same blocked jump or edge. When no complete route exists to the present authored patrol point, the actor freezes in place rather than skipping ahead to a later patrol point or marching toward an unreachable closest-approach cell."),
      paragraph("During active melee pursuit, route AI suspends route planning and falls back to direct combat pursuit so that combat does not burn route-planner time on the gameplay thread. Aggressive route AI may break off briefly to attack the player when the player enters the nearby engagement volume and then returns to the patrol path after the target leaves that range. Flexible route execution drives vertical support changes and longer jumps through an explicit edge-commit target, allowing the runtime to commit to takeoff edges for drops and longer jumps rather than braking early and falling off loosely."),
      paragraph("Free-roam and route AI use the same player collision, jump, placement, interaction, and kinematic stepping path as the local player. They can receive and deal melee knockback, flash red briefly when damaged, swing the visible attack arm during successful melee strikes, and use short jump-reset, knockback-reduction block placement, and bridge-placement heuristics while traversing and fighting whenever block placement is enabled for that instance."),
      paragraph("In survival mode, an aggressive AI attack lands only when the player is actually inside the AI eye-line within a three-block melee reach, while a peaceful AI does not attack. Local player left-clicks emit weak attack samples on empty swings, strong attack samples only on successful AI hits, and never stack weak and strong variants on the same click. Non-landing damage on the local player and damage on AI actors emit randomized player hit samples, and the first-person arm follows the same hurt-tint flash that modulates the player skin."),
      paragraph("Spawned AI players use the same skin pipeline as the local player, render through the same third-person player-model and shadow path, and persist independently inside each play space together with transform, health, behavior mode, personality, block-placement permission, route style, and route state."),
    ),
  ),
  AboutSection(
    title="Camera, HUD, skin, and video settings",
    blocks=(
      paragraph("Camera perspective is part of persistent runtime state. The default cycle order follows the Minecraft-style F5 sequence First Person, Third Person Back, Third Person Front, and First Person. The same action is remappable through the keybind settings, and the current perspective can also be selected explicitly from the video settings page."),
      code_block("First Person -> Third Person Back -> Third Person Front -> First Person"),
      paragraph("Third-person camera placement is collision-constrained against block collision volumes, so the camera retracts before penetrating nearby geometry and does not expose interior block faces by clipping through them. The third-person projection uses a smaller near plane together with a larger camera-clearance margin, keeping nearby block faces visible instead of allowing them to vanish at the lens boundary while the camera is pressed back against geometry."),
      paragraph("The gameplay crosshair is suppressed outside first person. Gameplay HUD rendering is remappable and defaults to F1 under Controls -> Gameplay Keys. When HUD rendering is enabled and the camera is in third person, the resolved session player name is projected above the player head in world space and in the pause preview, uses the same translucent F3-style background tone without a surrounding frame, fades when world geometry occludes the head or when the player is crouching, and disappears together with the rest of the gameplay HUD when F1 is used or the same setting is disabled from the controls window."),
      paragraph("The in-world name tag follows the rendered player-model base position rather than the raw physics body, so shallow step transitions do not produce overshoot-and-return motion. Crouch-release opacity restoration follows the live crouch input state rather than waiting for the eased crouch-eye offset to settle. The name tag is screen-composited from world projection and does not participate in shadow casting."),
      paragraph("The third-person player body and the first-person arm use a persistent slim-arm skin texture. The default texture remains Alex. A custom modern 64x64 skin can be imported from the pause menu, the imported file is overwritten in place under the app-managed data root as state/player_skin.png, and resetting returns the renderer to Alex. Both held blocks and held Othello control items follow the same swing state in the visible model and in the shadow caster, and Othello control item orientation is corrected consistently across first person, third person, and the shadow path."),
      paragraph("Step transitions drive the rendered player base height with the same vertical easing used by the camera eye, removing the previous shadow-only teleport impression while ascending or descending shallow ledges."),
      paragraph("Video settings are hosted in a separate application-modal settings window rather than inside an in-viewport overlay, so visual changes can be inspected against the live world while the window remains open. That window exposes the default Minecraft-style crosshair together with a persistent 16x16 pixel editor. A custom pattern can be drawn with the left mouse button, erased with the right mouse button, and reset through Clear Board, which simultaneously clears the editor board and restores the default Minecraft-style crosshair."),
      paragraph("The gameplay crosshair is rendered without the previous forced black outline, regardless of whether the active pattern is the default form or a user-authored bitmap. Cloud density and cloud seed follow the same enabled-state semantics used by view bobbing and camera shake, so disabling clouds visibly disables those sliders rather than leaving stale editable values on screen."),
      paragraph("The Video page exposes persistent break-particle spawn-rate and break-particle speed controls together with persistent minimum and maximum arm-rotation limits and a persistent arm-swing duration control that caps visible swing speed for the player model. The Game Player page retains the persistent block-break and block-place repeat interval controls alongside movement parameter controls and stores the explicit player name. Leaving that field blank keeps the pre-launch name dialog enabled and causes a new random session name to be generated at each restart."),
      paragraph("The detached settings shell includes this About page with creator attribution and a project overview, reusing the bundled Ludoxel title mark when no separate creator portrait asset is present in the repository."),
    ),
  ),
  AboutSection(
    title="Fullscreen and detached dialog behavior",
    blocks=(
      paragraph("When the detached settings window or the detached Othello settings window is opened while fullscreen is enabled, the host window temporarily returns to the normal state for the duration of that detached dialog and reapplies the stored fullscreen preference only after the detached window has closed. This preserves access to dialog controls without forcing the user to lose the persisted fullscreen preference merely to edit settings."),
      paragraph("The separate modal settings window remains live so that visual settings can be inspected against the world in real time. Time-based renderer motion such as cloud drift and animated-texture stepping is paused for true application deactivation and for pause, death, inventory, Othello-settings, and short-lived notice-dialog states."),
    ),
  ),
  AboutSection(
    title="Play Othello (Reversi)",
    blocks=(
      paragraph("Play Othello (Reversi) is a second persistent play space hosted inside the same application shell. It has its own hotbar, match settings, AI opponent, clocks, board interaction path, piece animation path, and rendering path. This mode is a specialized subsystem layered onto the renderer and UI framework, and it should be understood as a self-contained application mode rather than evidence that the surrounding sandbox has reached general game completeness."),
      paragraph("Within this space, block placement, block breaking, and the block inventory overlay are disabled. The Othello hotbar is reserved for control items. Slot 1 contains Start, and slot 9 contains Settings. Selecting either slot equips a dedicated enlarged control icon rather than leaving the hand empty. The icon is rendered as a single visible face in first person and is attached to the third-person player model and its shadow so that the active control item remains legible before use."),
      code_block("Slot 1: Start\nSlot 9: Settings"),
      paragraph("Right-clicking Start begins a fresh match or restarts the current match under the stored defaults. Right-clicking Settings opens a separate application-modal Othello settings window that configures AI strength, time control, disc-animation mode, player order, sacrifice level, worker count, hash level, and opening-book learning limits for the next match."),
      paragraph("The difficulty menu exposes Weak, Medium, Strong, Insane, and Insane+. Insane remains the cached bitboard-search engine without enforced opening-book selection, while Insane+ is the higher tier that consults the bundled and user-extended opening book before falling through to the same search core."),
      code_block("Weak\nMedium\nStrong\nInsane\nInsane+"),
      paragraph("The time-control menu exposes Timer off, one-move limits of 5, 10, and 30 seconds, and per-side limits of 1, 3, 5, 10, and 20 minutes. The animation menu exposes Animation off together with Ripple fast and Ripple slow, both of which start successive flips from the placed disc outward rather than rotating every captured disc at once."),
      code_block("Timer off\n1 move 5 seconds\n1 move 10 seconds\n1 move 30 seconds\n1 minute per side\n3 minutes per side\n5 minutes per side\n10 minutes per side\n20 minutes per side\nAnimation off\nRipple fast\nRipple slow"),
      paragraph("The settings window can extend the opening book by launching threshold-controlled learning with explicit depth, per-move error, cumulative error, and leaf-error bounds. The learning controls admit depth 0 through 60 with default 55, and per-move, cumulative, and leaf error bounds each admit 0 through 24 with defaults 22, 19, and 20. Starting book learning resets any active match state before the learning run begins, preventing clocks and board state from leaking into the learning session."),
      paragraph("A learning run exposes cancellable progress state, mirrors current status inside the detached settings window and the in-world Othello title HUD, temporarily projects the currently explored learning position onto the rendered board, and preserves partial progress on cancellation because user-generated book lines are written persistently under the app-managed data root as state/othello_opening_book.json. The compiled opening-book cache lives under cache/othello_opening_book_cache.json."),
      paragraph("Book storage is symmetry-aware at the position level through canonicalized board transforms, so search lookup and learning-state pruning treat rotated and reflected equivalents as the same opening-book position. A pristine persisted Othello state still renders the standard initial 2x2 opening discs before the first match is started. The default Othello configuration remains Medium, 20 minutes per side, Animation off, and player moves first."),
      paragraph("Disc placement is performed by aiming at the board and pressing the left mouse button on a legal square. Hovering reports the algebraic square name, such as a1 through h8. The Othello HUD uses the same panel style as the normal F3 debug HUD, is hidden whenever the ordinary F3 HUD is shown or gameplay HUD rendering is disabled with F1, and otherwise reports current turn, best move, principal line, player-versus-AI evaluation, and a painted evaluation line graph derived from the current search trace. The rendered board is hosted in a separate persistent world space, and match clocks pause while the pause menu or the separate Othello settings window is open."),
    ),
  ),
  AboutSection(
    title="Startup route and runtime shell",
    blocks=(
      paragraph("The canonical source-tree startup route is python -m ludoxel. The package entry path is rooted at src/ludoxel/__main__.py, after which control passes into ludoxel.application.bootstrap. The public project title is Ludoxel, while the current source package and import namespace remain ludoxel. This separation allows the visible application identity to evolve without forcing an immediate package-level rename across the codebase."),
      code_block("python -m ludoxel\nludoxel.application.bootstrap\nsrc/ludoxel/__main__.py"),
      paragraph("At startup, Ludoxel enforces a single desktop shell instance. If a second launch is attempted while an instance is already running, the currently visible top-level Ludoxel surface is restored, raised, and activated instead of opening a second process window."),
      paragraph("Before either the loading surface or the main window is shown, the shell loads the persisted player identity. When no explicit name is stored, it presents a dedicated player-name dialog in front of the loading screen. The dialog permits either an explicit name or an empty continuation. An empty value is intentionally preserved as no stored name, causing the runtime to generate a new random session name on each launch and to present the same dialog again on the next restart."),
      paragraph("After player identity resolution, the shell presents a dedicated top-level loading screen before the main window is allowed to surface. The embedded viewport still retains its in-window loading overlay until renderer initialization has completed and the initially visible chunk set has reached GPU residency. Both loading surfaces search bundled UI assets for the Ludoxel title mark and fall back to textual Ludoxel when no decodable asset is present."),
      code_block("assets/ui/ludoxel.png\nassets/ui/ludoxel.svg\nassets/ui/ludoxel.jpg\nassets/ui/ludoxel.jpeg\nassets/ui/ludoxel.webp\nassets/ui/ludoxel.bmp"),
      paragraph("Simulation input remains suspended during loading, so the user does not observe previous in-world hitching while initial chunk uploads converge, and the launch path no longer leaks an initial blank frame from a not-yet-initialized renderer surface. The persisted window rectangle and target monitor are restored before either the splash screen or the main window is shown, so relaunching returns the application to the previous display and window size rather than recentering it on the primary monitor."),
      paragraph("Space transfers between My World and Play Othello (Reversi) reuse a retained CPU-side chunk-build cache and immediately re-enter the same loading overlay while the target residency set remains unresolved. When the desktop shell becomes inactive, simulation input is suspended and mouse capture is released. The pause menu opens only when that deactivation occurred from ordinary captured gameplay. If the cursor had already been released because the user was in inventory or another non-captured state, the current screen remains in place instead of being replaced by an unsolicited pause surface."),
      paragraph("When the shell becomes active again, the viewport explicitly re-arms the next world upload and selection refresh so that returning from PAUSE or INVENTORY does not wait on stale render cadence before the world resumes stable drawing. Mouse-look capture enters a short resynchronization phase after capture is re-enabled. During that phase, the system cursor is repeatedly re-centered, keyboard movement continues to flow, camera delta is forced to zero, and normal mouse-look sampling resumes only after the cursor has remained at the viewport center across successive polls."),
      paragraph("On macOS, gameplay capture keeps keyboard interception and mouse confinement separate. The keyboard path installs the existing native CoreGraphics event tap, and the mouse path recenters the system cursor through a small CoreGraphics cursor-warp helper before falling back to Qt cursor positioning. The app bundle declares keyboard guard usage through NSInputMonitoringUsageDescription, and macOS may require Input Monitoring or Accessibility approval for that event tap to install. The pause-screen player preview preserves its last head orientation when the pointer leaves the application and resumes direct pointer tracking immediately when the pointer re-enters."),
    ),
  ),
  AboutSection(
    title="Source layout and responsibility boundaries",
    blocks=(
      paragraph("The source tree is organized by responsibility. ludoxel.foundations contains identity, repository and runtime root resolution, diagnostics, and mathematical kernels. ludoxel.simulation contains world state, generation, block catalogs, block models, movement rules, collision rules, gravity rules, picking, placement, interaction, player state, AI-player state, inventories, Othello rules, Othello engines, Othello books, and bundled Othello resources."),
      paragraph("ludoxel.application contains bootstrap, UI-independent preferences, persistence stores, integrity checking, session factories, session managers, runtime-state pipelines, render snapshot DTOs, and fixed-step runners. ludoxel.presentation contains Qt windows, input, HUD, overlays, settings surfaces, theme resources, renderer contracts, OpenGL and wgpu backends, shader resources, visual builders, and audio playback."),
      code_block("ludoxel.foundations\nludoxel.simulation\nludoxel.application\nludoxel.presentation"),
      paragraph("Package resources live under presentation/interface/theme, presentation/rendering/backends/opengl/shaders, presentation/rendering/backends/wgpu/shaders/sources, and simulation/spaces/othello/resources. Repository-level UI SVG and image assets remain under assets/ui. This layout keeps runtime code, package resources, repository assets, writable user state, and generated build outputs in distinct roles."),
      code_block("presentation/interface/theme\npresentation/rendering/backends/opengl/shaders\npresentation/rendering/backends/wgpu/shaders/sources\nsimulation/spaces/othello/resources\nassets/ui"),
    ),
  ),
  AboutSection(
    title="Native build and editable install model",
    blocks=(
      paragraph("The native build remains deliberately narrow. Only ludoxel.foundations.mathematics.geometry.ray_aabb, ludoxel.foundations.mathematics.voxels.dda, and ludoxel.foundations.mathematics.linear.view_angles are compiled in place. Those modules are dominated by scalar arithmetic, geometric branching, and dense numerical work."),
      code_block("ludoxel.foundations.mathematics.geometry.ray_aabb\nludoxel.foundations.mathematics.voxels.dda\nludoxel.foundations.mathematics.linear.view_angles"),
      paragraph("Broader scene and block orchestration layers remain in Python because they are governed primarily by Python object traffic, callback dispatch, dictionary access, and heterogeneous container traversal. Moving those layers wholesale across the extension boundary can reduce inspectability and worsen end-to-end frame cost."),
      paragraph("The supported recovery path for the acceleration layer is npm run build:native, which enters tools/build_native_extensions and verifies that the interpreter resolves those imports to compiled binaries instead of Python fallback sources. The editable install and explicit native build are intentionally separated. python -m pip install -e . is described by pyproject.toml and does not make Cython part of ordinary metadata evaluation. The explicit in-place native build performs the optional native compilation step through repository tooling and then verifies imported module targets."),
      code_block("python -m pip install -e .\nnpm run build:native\nnpm run build:native:check"),
      paragraph("On Windows, npm run build:windows is the primary executable packaging path and usually invokes the narrow native rebuild automatically unless --skip-native-build is supplied. The standalone npm run build:native path remains intentional for source-tree development, performance recovery after npm run clean, and any case in which in-place native modules are needed without rebuilding the Windows bundle."),
    ),
  ),
  AboutSection(
    title="Development workflow",
    blocks=(
      paragraph("The development path assumes Python 3.14.2 when available, PyQt6 6.6 or newer, and NumPy 1.26 or newer. The declared Python range is >=3.13,<3.15, so macOS environments without python3.14 may use python3.13 for ordinary source-tree development. On macOS, the platform dependency set includes wgpu and rendercanvas and does not require a platform OpenGL context. On Windows, the platform dependency set includes PyOpenGL and keeps the existing OpenGL renderer path."),
      paragraph("The intended Windows development path for a clean environment with only the editable source install creates .venv_ludoxel, activates it, updates pip tooling, installs the project in editable mode, and launches through python -m ludoxel."),
      code_block("python -m venv .venv_ludoxel\n.\\.venv_ludoxel\\Scripts\\Activate.ps1\npython -m pip install --upgrade pip setuptools wheel\npython -m pip install -e .\npython -m ludoxel"),
      paragraph("The intended macOS development path creates .venv_ludoxel with python3.14 when available, activates it through the POSIX shell path, updates pip tooling, installs the project in editable mode, and launches through python -m ludoxel. If python3.14 is not installed, python3.13 may be used for the virtual environment command while keeping the remaining commands unchanged."),
      code_block("python3.14 -m venv .venv_ludoxel\nsource .venv_ludoxel/bin/activate\npython -m pip install --upgrade pip setuptools wheel\npython -m pip install -e .\npython -m ludoxel"),
      paragraph("Development extras and the Node dependency tree are needed when local packaging, native extension rebuilding, or the repository check surface is required. If a native-accelerated module is edited, rerun npm run build:native. If packaging metadata, dependency declarations, entry-point definitions, or package-data rules are changed, rerun the editable install as well."),
      code_block("python -m pip install -e \".[dev]\"\nnpm install\nnpm run build:native\nnpm run build:native:check\npython -m pip install -e ."),
      paragraph("On Windows, a loaded .pyd file cannot be overwritten while a Python process still holds the module image open. If the in-place native build fails with a file-in-use or permission error, terminate the running application and any interactive Python processes that imported the target module, then rerun the build."),
      code_block("taskkill /F /IM python.exe\nnpm run build:native"),
      paragraph("The repository-local cleanup tool deliberately removes generated native extension files. After npm run clean removes them, npm run build:native must be rerun before the next performance-sensitive session because the application will otherwise import the slower Python fallback kernels until the rebuild completes."),
      code_block("npm run clean\nnpm run build:native\npython -m build"),
    ),
  ),
  AboutSection(
    title="Windows and macOS packaging",
    blocks=(
      paragraph("The supported Windows executable packaging path is npm run build:windows. The tool rebuilds the native hot-path extensions unless --skip-native-build is supplied, invokes PyInstaller in one-file mode using src/ludoxel/__main__.py as the frozen entry script, collects package data under src/ludoxel, and bundles both the repository-level assets tree and repository-level src tree into the PyInstaller data root resolved through sys._MEIPASS."),
      paragraph("The frozen process loads immutable bundled resources from the internal extraction root while keeping runtime writes in the user-specific app-managed data root. PyInstaller onefile still performs its own temporary extraction into the operating-system temporary directory before control reaches the application. The builder removes obsolete onedir output on a best-effort basis, allocates run-unique work, spec, and staging directories, publishes the staged Ludoxel.exe into dist/windows/Ludoxel.exe when possible, and preserves the staged executable when the published path is locked by a running previous build."),
      code_block("npm run build:windows\ndist\\windows\\Ludoxel.exe\ndist\\windows\\LICENSE\ndist\\windows\\NOTICE\ndist\\windows\\third-party\\"),
      paragraph("If a custom Windows executable icon is desired, the canonical path is assets/ui/app_icon.ico. When that file exists, tools/build_desktop_app forwards it to PyInstaller through --icon so the generated Ludoxel.exe carries the custom shell icon. The running Qt application also searches bundled resources for app_icon.ico, app_icon.png, app_icon.jpg, and app_icon.jpeg, but only the .ico file is suitable for embedding into the Windows executable itself."),
      code_block("assets/ui/app_icon.ico\nassets/ui/app_icon.png\nassets/ui/app_icon.jpg\nassets/ui/app_icon.jpeg"),
      paragraph("The frozen Windows entry path enables multiprocessing freeze support before control reaches the application shell, assigns an explicit Windows AppUserModelID for the Ludoxel desktop identity, and suppresses visible console windows for diagnostic tasklist and nvidia-smi probes that may be used by the optional debug HUD."),
      paragraph("The macOS packaging command surface is the supported local app-bundle verification path. It builds a PyInstaller .app, preserves the bundled Python.framework symlink layout, bundles assets, LICENSE, NOTICE, and third-party material, verifies bundled fonts under assets/fonts, records the gameplay input monitoring usage string for the keyboard guard in Info.plist, re-signs the bundle after that Info.plist patch, and forwards a macOS icon only when a real .icns asset is present."),
      code_block("npm run build:macos\nnpm run build:macos:check\nnpm run build:macos -- --status"),
      paragraph("The macOS packaging path remains distinct from the explicit local optimization path. The repository does not make Cython execution an implicit side effect of every packaging or installation action, while the supported Windows bundle builder executes the narrow native build automatically because measured renderer frame rate depends materially on the three compiled kernels being present. Codesigning and notarization remain separate release steps."),
    ),
  ),
  AboutSection(
    title="Repository command surface",
    blocks=(
      paragraph("Development support is entered through package.json and tools. The root-level scripts directory is not part of the supported structure. The command surface covers help, check, CI, formatting, linting, directory export, tool tests, package checks, documentation checks, license checks, resource checks, shader checks, native build recovery, desktop packaging, cleanup, and audio-asset conversion."),
      code_block("npm run help\nnpm run check\nnpm run ci\nnpm run format\nnpm run format:check\nnpm run format:py\nnpm run format:py:check\nnpm run lint\nnpm run lint:js\nnpm run lint:css\nnpm run lint:py\nnpm run tools:export\nnpm run tools:export -- --target root --exclude \"folder:assets\" --exclude \"ext:.so\"\nnpm run tools:test\nnpm run package:check\nnpm run docs:check\nnpm run license:check\nnpm run resources:check\nnpm run shader:check"),
      paragraph("The active tool directories are help_commands, check_project, build_native_extensions, build_desktop_app, clean_build_artifacts, export_directory_markdown, format_python_source, format_web_source, and convert_audio_assets. Each command owns its help path. --help and --lang ja|en are supported by check commands, and npm run help -- <command> gives the repository command overview where applicable."),
      code_block("tools/help_commands\ntools/check_project\ntools/build_native_extensions\ntools/build_desktop_app\ntools/clean_build_artifacts\ntools/export_directory_markdown\ntools/format_python_source\ntools/format_web_source\ntools/convert_audio_assets"),
      paragraph("Python source uses 2-space indentation. format:py and lint:py enforce that policy without asking Ruff to rewrite Python into a 4-space style. tools/check_project keeps check implementations under check-specific folders such as src/check/package/package.check.mjs, rather than placing package.check.mjs, docs.check.mjs, legal.check.mjs, resources.check.mjs, or shaders.check.mjs directly under a generic service folder."),
      paragraph("tools/convert_audio_assets reports .ogg ambient audio and optional generated .wav derivatives. npm run assets:audio:check reports missing generated .wav files as warnings because the current ambient catalog directly references .ogg. npm run assets:audio:check -- --require-wav is available when a packaging target requires generated .wav derivatives."),
    ),
  ),
  AboutSection(
    title="Runtime data and tamper detection",
    blocks=(
      paragraph("Immutable application resources stay with the bundled resource root. Runtime-writable data does not use repository-level configs as the normal save location. ludoxel.foundations.locations.roots.default_runtime_data_root resolves the app-managed data root, honoring LUDOXEL_DATA_ROOT when explicitly set. On Windows, the default root is under the user's local application data directory."),
      code_block("LUDOXEL_DATA_ROOT\nstate/\ncache/\nstate/state_manifest.json\nstate/integrity_key.bin"),
      paragraph("The app-managed data root is split into state and cache. Player settings, window state, world edits, custom player skin, and the Othello user opening-book extension are state. The compiled Othello opening-book map is cache. The main state files are covered by state/state_manifest.json and state/integrity_key.bin using HMAC-SHA256 to detect simple external edits or accidental corruption."),
      paragraph("This integrity path is tamper detection, not an absolute guarantee against a local user who can rewrite both data files and the local integrity key. An existing repository-level configs directory is treated only as previous-format input for migration and compatibility. New runtime writes go to the app-managed data root."),
    ),
  ),
  AboutSection(
    title="Legal material and repository policy",
    blocks=(
      paragraph("Ludoxel Original Materials are governed by LicenseRef-All-Rights-Reserved under the Ludoxel Independent License in LICENSE. The repository is not open source and is not licensed under Apache-2.0. Public visibility, hosting-service browsing, cloning, downloading, or the presence of repository source code does not grant a copyright license beyond the permissions stated in the license."),
      paragraph("NOTICE is written in Japanese and records the relationship between Ludoxel Original Materials, third-party materials, provenance-sensitive local assets, runtime user data, and distribution legal material. Third-party license texts are kept under third-party. Kaisei Opti is documented under third-party/kaisei-opti with the SIL Open Font License text."),
      code_block("LICENSE\nNOTICE\nthird-party/\nthird-party/kaisei-opti/\nassets/fonts/"),
      paragraph("Desktop builds must bundle the fonts under assets/fonts, and runtime startup registers bundled fonts rather than relying on platform system-font fallback. Local Minecraft-named assets and fonts under assets are not covered by the Ludoxel Independent License and must not be represented as original Ludoxel assets. Their redistribution rights are not established by this repository."),
      paragraph("The .github directory mirrors the non-open-source governance boundary used by the reference Sudoku project: external contributions are not accepted, issue forms are limited, security reporting is separated, Dependabot is scoped, and CI runs the same npm entrypoint used locally."),
    ),
  ),
  AboutSection(
    title="Shader and platform notes",
    blocks=(
      paragraph("The renderer target is selected by platform. Windows uses the existing PyOpenGL renderer and its OpenGL 4.3 contract. macOS uses wgpu-native through a Qt rendercanvas surface, reaching Metal through wgpu-native rather than using Apple's OpenGL implementation."),
      code_block("Windows: PyOpenGL / OpenGL 4.3\nmacOS: wgpu-native / rendercanvas / Metal"),
      paragraph("npm run shader:check validates package shader roots under src/ludoxel/presentation/rendering/backends/opengl/shaders and src/ludoxel/presentation/rendering/backends/wgpu/shaders/sources. It keeps obvious cross-profile hazards, such as raw gl_VertexID use, out of source."),
      code_block("src/ludoxel/presentation/rendering/backends/opengl/shaders\nsrc/ludoxel/presentation/rendering/backends/wgpu/shaders/sources\nnpm run shader:check"),
      paragraph("The macOS renderer path does not compile or link chunk_face_payload.comp and does not require GLSL 4.30 compute shaders, shader storage buffers, or glMultiDrawArraysIndirect. The Windows renderer path still uses the existing OpenGL implementation until it can be migrated and verified on Windows hardware."),
      paragraph("The macOS app packaging path uses the wgpu-native renderer path, collects the Python wgpu and rendercanvas packages for PyInstaller, preserves bundled assets, fonts, icon metadata, the gameplay input monitoring usage string, Python framework links, and legal material, and verifies the app-bundle shape during npm run build:macos:check. Windows packaging keeps the existing PyOpenGL renderer path and Windows .ico handling."),
    ),
  ),
)
