# SPDX-FileCopyrightText: 2026 Kento Konishi
# SPDX-License-Identifier: LicenseRef-All-Rights-Reserved
from __future__ import annotations

from dataclasses import dataclass

PROFILE_IMAGE_CANDIDATE_NAMES: tuple[str, ...] = ("profile.png", "profile.jpg", "profile.jpeg", "profile.webp", "profile.bmp")
GITHUB_IMAGE_CANDIDATE_NAMES: tuple[str, ...] = ("github.png", "github.jpg", "github.jpeg", "github.webp", "github.bmp", "github.svg")
ABOUT_GITHUB_URL = "https://github.com/5uog/Ludoxel/"

ABOUT_CREATOR_DISPLAY_NAME = "Kento Konishi"
ABOUT_CREATOR_HANDLE = "5uog"
ABOUT_CREATOR_ROLE = "Keio University student / Ludoxel creator"
ABOUT_CREATOR_AGE = "20"
ABOUT_CREATOR_GENDER = "he/him"

ABOUT_PROFILE_BIO_TEXT: str = "My academic work is directed toward future legal practice, with particular concern for victim protection, fact finding, procedural access, information management, and institutional reform. Law is the principal field of that study. Information security, software architecture, persistence design, interface construction, and verification supply an adjacent technical discipline for examining how protective systems can remain inspectable, explainable, testable, and accountable when they process human claims, evidence, access routes, stored information, and institutional decisions. Ludoxel is developed as a separate personal desktop software project, but it shares that discipline of explicit structure: state must be preserved deliberately, renderer behavior must be observable, input ownership must be controlled, and user-facing systems must be described in terms precise enough to be tested."

ABOUT_WORK_TEXT: str = "I work on Ludoxel as a PyQt6 desktop application with persistent voxel-world state, first-person and third-person camera behavior, collision, picking, block-state rendering, falling-block simulation, AI-player behavior and route planning, a separate Othello play space, platform-specific OpenGL and wgpu renderer paths, app-managed runtime persistence, bundled resources, desktop packaging, and application-facing documentation."

ABOUT_ACADEMIC_DIRECTION_TEXT: str = "My academic direction centers on legal practice, victim protection, fact finding, procedural access, information management, and institutional reform. Software-system design is relevant to that direction because protective institutions also depend on inspectable architecture, controlled state, reliable access paths, durable records, explicit procedures, and explanations that remain accurate when a system is used by a person rather than only described by its designer."

ABOUT_ETYMOLOGY_PARAGRAPHS: tuple[str, ...] = (
  "Latin 'ludus' underlies the initial element 'lud-'. Its attested semantic field extends across play, game, sport, school, and training. The stem therefore carries a broad ludic reference: play as a general class of rule-bound or exploratory activity, rather than one combat form, one genre, or one fixed rule set.",
  "'Voxel' is the modern technical contraction of 'volumetric' and 'pixel'. In technical usage, it denotes a discrete element of three-dimensional representation, commonly treated as the spatial analogue of the pixel, and therefore refers to discretized volume rather than to a merely visual style or atmospheric motif.",
  "'Ludoxel' accordingly denotes ludic activity conducted in voxel space. As the title of a sandbox desktop application, the term is operationally exact: the represented environment is voxel-constituted, while the admitted activity remains broadly ludic, extending across local manipulation, traversal, authored routes, AI observation, and a separate board-game space hosted inside the same shell.",
)


@dataclass(frozen=True)
class AboutBlock:
  kind: str
  text: str


@dataclass(frozen=True)
class AboutSection:
  title: str
  blocks: tuple[AboutBlock, ...]


def paragraph(text: str) -> AboutBlock:
  return AboutBlock(kind="paragraph", text=str(text))


def code_block(text: str) -> AboutBlock:
  return AboutBlock(kind="code", text=str(text))


ABOUT_PROJECT_OVERVIEW_SECTIONS: tuple[AboutSection, ...] = (
  AboutSection(
    title="Ludoxel v3.6",
    blocks=(
      paragraph("Ludoxel v3.6 is a PyQt6 desktop application that integrates a persistent restricted voxel sandbox, first-person and third-person camera behavior, explicit block-state geometry, collision and picking rules, falling-block simulation, AI-player behavior, route authoring, a separate persistent Othello play space, platform-specific renderer backends, app-managed persistence, desktop packaging, bundled resources, and repository-level verification into one inspectable software system. The project is best understood as an engineering study of how a small but stateful voxel application can make its runtime state, renderer behavior, input ownership, persistence semantics, and distribution boundary explicit enough to be audited from code, documentation, and user-facing settings surfaces."),
      paragraph("The application title is Ludoxel, while the import namespace remains `ludoxel`. The canonical source-tree execution path is `python -m ludoxel`, rooted at `src/ludoxel/__main__.py`, which calls `multiprocessing.freeze_support()` and then enters `ludoxel.application.run_app`. The application package facade resolves `run_app` through `ludoxel.application.bootstrap`, and `ludoxel.application.bootstrap.run.run_app()` resolves the project root, bundled resource root, and app-managed data root before installing Othello opening-book storage hooks and transferring control to the Qt desktop shell. This startup route is intentionally concrete: bootstrap owns root resolution and composition, application persistence owns saved state, simulation owns domain behavior, and presentation owns Qt windows and renderer surfaces."),
      paragraph("Ludoxel exposes two persistent application modes inside the same desktop shell: `My World` and `Play Othello (Reversi)`. `My World` is the ordinary sandbox and inspection space, while `Play Othello (Reversi)` is a second persistent play space with its own board state, clocks, AI opponent, control hotbar, match settings, animation path, opening-book storage, and renderer integration. Both spaces share the same shell, renderer contract boundary, preference system, modal-window policy, title-mark search path, runtime data root, and save discipline, yet each space preserves its own player transform, world state, AI state, and mode-local session state."),
      paragraph("The term restricted voxel-world model is used here in a deliberately technical sense. Ludoxel does not claim general completeness as a Minecraft implementation. It selects a bounded subset of block families, interaction rules, survival-like damage behavior, structural updates, and rendering passes so that the relationship between `WorldState`, `BlockDefinition`, block-state parsing, collision AABBs, pick AABBs, render boxes, chunk payload generation, GPU upload tracking, renderer snapshots, and persistence files remains directly inspectable. That narrower scope gives the codebase an experimental value that would be obscured by a broader but less verifiable catalog."),
      code_block("title: Ludoxel\npackage namespace: ludoxel\ncurrent package version: 3.6.0\nsource entry: src/ludoxel/__main__.py\nbootstrap function: ludoxel.application.bootstrap.run.run_app\nconsole script: ludoxel = ludoxel.application.bootstrap:run_app\nprincipal GUI toolkit: PyQt6 >=6.6,<7\nPython range: >=3.13,<3.15\npersistent play spaces: My World, Play Othello (Reversi)\nprimary renderer families: Windows OpenGL backend, macOS wgpu backend\nabout content owner: src/ludoxel/presentation/interface/settings/about/content.py\nabout data structures: AboutSection, AboutBlock\nabout block constructors: paragraph(text), code_block(text)"),
    ),
  ),
  AboutSection(
    title="Layered source architecture",
    blocks=(
      paragraph("The source tree is divided into `ludoxel.foundations`, `ludoxel.simulation`, `ludoxel.application`, and `ludoxel.presentation`. This is an import and responsibility architecture, not a cosmetic folder taxonomy. `foundations` contains identity, runtime and repository root resolution, diagnostics, scalar coercion, numeric utilities, vector and matrix operations, view-angle kernels, AABB and ray mathematics, voxel DDA traversal, chunk-coordinate functions, and frustum clipping. `simulation` contains world state, generation fixtures, block registries, block-state codecs, block model geometry, structural connectivity, player and AI-player state, inventories, movement, collision, gravity, placement, picking, My World, and Othello rules, engines, books, and resources. `application` contains bootstrap, UI-independent preferences, persistence schemas, JSON stores, HMAC manifest handling, session factories, session managers, render-snapshot DTO pipelines, runtime-state application, and fixed-step runners. `presentation` contains Qt windows, input adapters, HUD widgets, overlays, settings pages, theme resources, audio playback, renderer contracts, OpenGL and wgpu backends, shader resources, visual-state builders, and viewport lifecycle code."),
      paragraph("The dependency direction follows the semantic order of those responsibilities. Foundations can be used by all higher layers. Simulation can use foundations and must remain independent of Qt widgets, renderer backends, packaging tools, and JSON-store policy. Application can connect simulation to persistence and session runtime, while presentation can consume application and simulation state to display, edit, render, and play sound. The one deliberate exception is the composition root in `application.bootstrap.run`, which imports the presentation shell after roots and storage hooks are resolved. This exception localizes the unavoidable final connection between UI-independent startup and the Qt desktop application."),
      paragraph("The architecture matters because Ludoxel stores and renders stateful objects whose meaning must survive across multiple paths. A player position stored through `PersistedPlayer`, a block encoded through `WorldState.to_persisted_dict()`, a hotbar encoded through `PersistedInventory`, an AI route encoded through `PersistedAiPlayer`, and an Othello match stored through `PersistedOthelloSpace` must continue to mean the same thing when later consumed by a session manager, a collision resolver, a renderer snapshot, a HUD payload, or a settings surface. That condition requires an explicit boundary between domain state, persistence representation, UI controls, and backend rendering resources."),
      code_block("top-level package layers:\n  ludoxel.foundations\n  ludoxel.simulation\n  ludoxel.application\n  ludoxel.presentation\n\napplication-level public route:\n  src/ludoxel/__main__.py\n  -> ludoxel.application.run_app\n  -> ludoxel.application.bootstrap.run.run_app\n  -> ludoxel.presentation.interface.windows.main.run_app\n\nrepresentative package resource roots:\n  ludoxel/presentation/interface/theme/*.qss\n  ludoxel/presentation/rendering/backends/opengl/shaders/*.vert, *.frag, *.comp, common/*.glsl\n  ludoxel/presentation/rendering/backends/wgpu/shaders/sources/*.vert, *.frag, *.comp, common/*.glsl\n  ludoxel/simulation/spaces/othello/resources/*.json"),
    ),
  ),
  AboutSection(
    title="Desktop shell and mode switching",
    blocks=(
      paragraph("The desktop shell owns the transition between the two persistent play spaces. The pause menu exposes `Play My World`, `Play Othello (Reversi)`, and `Save & Quit`. A destination action is disabled while its target space is already active, and `Save & Quit` persists the current world, player state, active space, settings, inventory branch, Othello configuration, and mode-local session data before application closure. The shell therefore treats space switching as a state transition inside a single application instance rather than as a process restart or a transient menu action."),
      paragraph("The pause surface is also part of the renderer and input contract. The left half hosts the Ludoxel title mark and session controls, while the right half hosts a live slim-arm player preview with skin import and reset actions. The preview interaction path supplies desired view angles to the renderer API, so the pause page does not duplicate skin UV logic, cube layout, or body-preview geometry. The preview body rotates around the vertical axis while the left mouse button is held, head yaw remains a bounded offset from body heading, and pitch follows screen-space vertical direction. When third-person camera mode and gameplay HUD rendering are both active, the preview reuses the in-world name-tag treatment above the head."),
      paragraph("Startup and reactivation are also shell-level behaviors. The application enforces a single desktop shell instance, restores an existing window when a second launch is attempted, loads persisted player identity before the loading surface, presents a player-name dialog when no explicit name is stored, restores persisted window geometry and target monitor before the splash or main window appears, and keeps simulation input suspended while renderer initialization and initially visible chunk residency converge. These behaviors tie desktop UX to runtime state correctness: the user should not observe a blank initial renderer frame, an unsolicited duplicated process window, or input advancing the simulation before the visible world is resident."),
      code_block("persistent shell actions:\n  Play My World\n  Play Othello (Reversi)\n  Save & Quit\n\nstartup resource title search order:\n  assets/ui/ludoxel.png\n  assets/ui/ludoxel.svg\n  assets/ui/ludoxel.jpg\n  assets/ui/ludoxel.jpeg\n  assets/ui/ludoxel.webp\n  assets/ui/ludoxel.bmp\n\nshell-level invariants:\n  single desktop instance\n  persisted player identity before main window\n  persisted window rectangle and monitor before surface display\n  loading overlay until renderer initialization and initial chunk residency\n  retained CPU-side chunk-build cache across space transfer"),
    ),
  ),
  AboutSection(
    title="Runtime persistence and tamper detection",
    blocks=(
      paragraph("Runtime data is stored under the app-managed data root resolved by `ludoxel.foundations.locations.roots.default_runtime_data_root`, with `LUDOXEL_DATA_ROOT` accepted as an explicit override. The data root is split into `state` and `cache`. Player settings, window state, world edits, custom crosshair pixels, imported player skin, AI actors, active space, Othello match state, Othello settings, and user-generated Othello opening-book lines are state. The compiled Othello opening-book lookup map is cache. Repository-level `configs` is treated as previous-format input for migration and compatibility; v3.6 runtime writes are directed to the app-managed root."),
      paragraph("Application persistence is encoded through explicit schema classes. `PlayerStateFile` serializes version `7`, current play-space id, settings, inventory, and Othello settings. `WorldStateFile` serializes version `3` and contains `PersistedPlaySpace` for My World and `PersistedOthelloSpace` for Othello. `PersistedSettings` records FOV, mouse sensitivity, inversion flags, selection outline, cloud, wireframe, shadow, sun, creative mode, repeated-interaction intervals, particle controls, movement parameters, camera mode, fullscreen state, view bobbing, camera shake, arm animation, render distance, debug flags, HUD state, window geometry, keybinds, and audio preferences. `PersistedPlayer` records position, velocity, yaw, pitch, ground state, flying state, auto-jump cooldown, crouch-eye offset, health, and maximum health. `PersistedAiPlayer` records actor id, behavior mode, personality, placement permission, held item, transform, velocity, view angles, health, ground state, flight state, route points, route closure, route execution state, route style, and route target index."),
      paragraph("The integrity layer is implemented in `application.persistence.integrity.manifest`. `update_runtime_integrity_manifest()` creates or loads a 32-byte local integrity key, computes HMAC-SHA256 over the protected relative path, a null separator, and streamed file data, then writes `state/state_manifest.json`. `verify_runtime_file()` reads the manifest, loads `state/integrity_key.bin`, recomputes the digest, and compares it with `hmac.compare_digest`. The protected path set includes `state/player_state.json`, `state/world_state.json`, `state/player_skin.png`, and `state/othello_opening_book.json`. This mechanism detects simple external edits and accidental corruption of user-writable runtime files while preserving the project’s explicit limitation that a local user with control over both data and key material can rewrite the verification basis."),
      code_block("persistence schema classes:\n  AppState\n  PlayerStateFile(version=7)\n  WorldStateFile(version=3)\n  PersistedSettings\n  PersistedInventory\n  PersistedPlayer\n  PersistedWorld\n  PersistedAiPlayer\n  PersistedPlaySpace\n  PersistedOthelloSpace\n\nstate files:\n  state/player_state.json\n  state/world_state.json\n  state/player_skin.png\n  state/othello_opening_book.json\n  state/state_manifest.json\n  state/integrity_key.bin\n\ncache files:\n  cache/othello_opening_book_cache.json\n\nintegrity functions:\n  verify_runtime_file(data_root, relative_path)\n  update_runtime_integrity_manifest(data_root, relative_paths)\n\nintegrity algorithm: hmac-sha256\nintegrity key length: 32 bytes\nstreaming chunk size: 1024 * 1024 bytes"),
    ),
  ),
  AboutSection(
    title="My World simulation and survival state",
    blocks=(
      paragraph("`My World` is the ordinary persistent sandbox space. It serves as the inspection environment in which the implemented block subset can be placed, broken, rendered, picked, collided against, structurally updated, saved, and restored. The implemented block families include full cubes, slabs, stairs, fences, fence gates, and walls, each governed by block-state logic for render boxes, collision volumes, pick volumes, structural connectivity, top support, neighbor updates, and renderer payload extraction. The world model remains deliberately bounded in breadth, while the implemented subset is required to stay coherent across simulation, rendering, interaction, and persistence."),
      paragraph("The local player uses a survival-health path outside creative mode. The health pool is `20` points. Fall damage follows Minecraft-like threshold semantics, and lethal damage enters the ordinary death-and-respawn flow. Falling below `y = -64` applies repeated void damage on a fixed half-second cadence until health reaches zero, instead of triggering an immediate scripted death surface. This distinction matters because damage, death overlay, respawn, camera position, player tint, HUD health display, and persisted player state remain connected to the same health model."),
      paragraph("The collision path includes depenetration for pre-existing overlap, which prevents block edits and restored states from leaving the camera embedded in geometry. Closed fence gates preserve the special case in which a player already standing inside the gate is not expelled when the gate closes around them, and landed gravity blocks similarly preserve overlap when settling onto the player. Persisted-state restoration reconstructs those exemptions before the first post-load collision step, which makes relaunch behavior consistent with the runtime rule that created the overlap."),
      code_block("My World characteristics:\n  persistent sandbox space\n  block placement enabled\n  block breaking enabled\n  creative inventory enabled\n  AI special item enabled\n  player transform persisted per space\n  local world edits persisted per space\n  AI players persisted per space\n\nsurvival values:\n  health pool: 20 points\n  void threshold: y = -64\n  void damage cadence: 0.50 s\n\nimplemented structural block families:\n  full cubes\n  slabs\n  stairs\n  fences\n  fence gates\n  walls\n\nstate-sensitive geometry paths:\n  render boxes\n  collision volumes\n  pick volumes\n  structural connectivity\n  top support\n  neighbor updates"),
    ),
  ),
  AboutSection(
    title="World state, generation fixture, and chunk model",
    blocks=(
      paragraph("World storage is represented by `simulation.worlds.state.world.WorldState`. The class stores block data, revision state, dirty chunk state, chunk indexing, column indexing, mesh-revision tracking, gravity-dirty columns, and synchronization around internal mutation. Its public behavior includes cell mutation, bulk mutation, block removal, chunk-build snapshots, bounded block-window snapshots, column snapshots, persisted serialization, persisted deserialization, and whole-world replacement. This makes `WorldState` the authoritative CPU-side model from which collision, gravity, interaction, persistence, and renderer submission derive their respective views."),
      paragraph("The current initial sandbox generation remains a flat inspection fixture. `generate_flat_world()` defaults to `half_extent = 32`, `ground_y = 0`, and `block_id = \"minecraft:grass_block\"`. The generated square covers coordinates from `-32` through `32` on both horizontal axes, giving a side length of `65` cells and an initial floor area of `4225` placed ground blocks before user edits, falling-block transitions, AI route changes, or Othello-space separation are considered. `generate_test_map()` delegates to this flat generator, so the baseline space is a reproducible world fixture rather than an accidental fallback."),
      paragraph("Chunk addressing is based on `CHUNK_SIZE = 16`. `chunk_key(x, y, z)` maps world coordinates to chunk coordinates, `chunk_origin()` reconstructs chunk origins, and `neighbor_chunk_keys_for_cell()` marks adjacent chunks when an edit occurs on a boundary. Renderer residency is coordinated by `WorldUploadTracker`, which separates authoritative world state from backend upload state. The tracker can retain CPU-side build results across space transitions, prefetch around the visible chunk set, drain completed worker results in bounded batches, evict stale chunks, and expose residency completion to loading overlays."),
      code_block("world classes and functions:\n  WorldState\n  generate_flat_world(half_extent=32, ground_y=0, block_id=\"minecraft:grass_block\")\n  generate_test_map(seed=0)\n  chunk_key(x, y, z)\n  chunk_origin(chunk_key_value)\n  neighbor_chunk_keys_for_cell(x, y, z)\n  WorldState.set_block()\n  WorldState.remove_block()\n  WorldState.set_blocks_bulk()\n  WorldState.snapshot_for_chunk_build()\n  WorldState.snapshot_block_window()\n  WorldState.snapshot_column()\n  WorldState.to_persisted_dict()\n  WorldState.from_persisted_dict()\n  WorldState.replace_all()\n\nworld constants and fixture values:\n  CHUNK_SIZE: 16\n  default flat half extent: 32\n  default flat ground y: 0\n  default flat floor side length: 65\n  default flat floor cells: 4225\n  default render distance: 6 chunks\n  render distance clamp: 2..50 chunks"),
    ),
  ),
  AboutSection(
    title="Block-state geometry and structural rules",
    blocks=(
      paragraph("Ludoxel does not reduce a block to a texture name. A block is represented through `BlockDefinition`, texture declarations, block-state parsing and formatting, property accessors, registry construction, model-specific geometry, structural connectivity rules, support rules, collision AABBs, pick AABBs, and renderer-facing render boxes. The same encoded state string that appears in world persistence must be sufficient for placement, breaking, picking, collision, rendering, structural neighbor updates, and support evaluation. This is the reason the block model layer contains family-specific modules for slabs, stairs, fences, fence gates, and walls instead of representing every non-full cube as an untyped decorative mesh."),
      paragraph("The geometry model works in block-local unit space with Minecraft-like sixteenth-block conventions. Slabs alter vertical occupancy by half-block state. Stairs introduce facing and shape-dependent geometry. Fences and walls introduce central posts and arms whose existence and height depend on neighboring blocks and top-support conditions. Fence gates introduce facing, open state, and in-wall state, and their collision shape differs from their open visual state. Wall top-support updates account for the currently implemented families above the wall, including full cubes, fences, fence gates, slabs, stairs, and other walls. These rules ensure that a partial block can be rendered, selected, collided against, used as a falling-block support, or evaluated as a structural neighbor through the same state vocabulary."),
      paragraph("The useful academic term for this design is state-parametric voxel geometry. In this project, that term means that the geometry of a block is a function of its block id, encoded properties, surrounding block states, and requested purpose. A render box, a collision volume, a pick volume, a top-support result, and a structural update can differ while remaining derived from the same block-state source. This term is introduced because ordinary phrases such as block mesh or cube model are too imprecise for Ludoxel’s implementation, where thin members, half-height supports, gate openness, wall posts, and connected arms materially affect both physics and rendering."),
      code_block("block model classes and functions:\n  BlockDefinition\n  BlockTextures\n  BlockRegistry\n  create_default_registry()\n  parse_state()\n  format_state()\n  prop_as_bool()\n  collision_aabbs_for_block()\n  render_boxes_for_block()\n  pick_boxes_for_block()\n  pick_aabbs_for_block()\n  has_full_top_support_for_block()\n  collect_structural_neighbor_updates()\n\nblock family modules:\n  definitions/block.py\n  models/common.py\n  models/dimensions.py\n  models/slab.py\n  models/stairs.py\n  models/fence.py\n  models/fence_gate.py\n  models/wall.py\n  structures/cardinal.py\n  structures/connectivity.py\n  structures/neighborhood.py\n  structures/structural_rules.py\n\nimplemented partial-volume families:\n  slabs\n  stairs\n  fences\n  fence gates\n  walls"),
    ),
  ),
  AboutSection(
    title="Interaction service, placement route state, and repeated actions",
    blocks=(
      paragraph("Block interaction is coordinated through `InteractionService` and related placement, breaking, picking, and toggle functions. The interaction layer does not merely receive mouse clicks; it binds ray selection, block-state resolution, player-overlap rejection, slab merging, stair orientation, fence-gate toggling, structural neighbor updates, falling-block conversion, world revision advancement, and audio or particle consequences into one service path. This arrangement prevents viewport code from becoming the owner of gameplay semantics."),
      paragraph("Repeated interaction is persisted as runtime preference state. Creative-mode left-button breaking repeats at `0.30 s`. Right-button placement preserves the initial click as a single isolated placement, arms only after an initial `0.20 s` dwell, and then resumes at a high-cadence continuation interval of approximately `0.008 s`, matching the `1 / 120` fixed-step timing used by the simulation. Right-button interaction for fence gates repeats at `0.20 s`. These cadences are not arbitrary UI animation values; they determine the relationship between physical movement, collision resolution, placement legality, held route progression, and visible block materialization."),
      paragraph("Held placement is route-constrained. A sequence can begin from a directly visible horizontal side face, from a supporting ground condition that synthesizes a side-face basis for crouch bridging, from a generic horizontal start, or from a first-follow-up vertical branch. The maintained frontier advances only after the attempted target cell actually contains a valid world block at that exact location. A failure caused by player overlap, missing support, rejected state, or gravity-affected unsupported conversion leaves the route state unchanged. This prevents a held placement sequence from skipping through absent blocks, turning an established bridge into an obsolete tower, or using a falling block as a false continuation support after it has already left the static world."),
      code_block("interaction classes and functions:\n  InteractionService\n  PlacementPolicy\n  pick_block_for_session()\n  break_block_for_session()\n  place_block_from_hit_for_session()\n  place_block_for_session()\n  interact_block_at_hit_for_session()\n  resolve_place_state()\n  choose_half_type()\n  toggle_fence_gate_if_hit_for_service()\n  player_intersects_state_for_service()\n\npersistent interaction cadences:\n  block_break_repeat_interval_s: 0.30\n  block_place_repeat_initial_delay_s: 0.20\n  block_place_repeat_interval_s: approximately 0.008 s\n  block_interact_repeat_interval_s: 0.20\n\nkey defaults:\n  movement: W, A, S, D\n  jump: Space\n  crouch: Shift\n  sprint: Control\n  inventory: E\n  creative mode: B\n  gameplay HUD: F1\n  debug HUD: F3\n  debug shadow: F4\n  camera perspective cycle: F5\n  clear selected slot: Q\n  hotbar slots: 1..9"),
    ),
  ),
  AboutSection(
    title="Falling blocks and particle sampling",
    blocks=(
      paragraph("Gravity-affected blocks are modeled as a transition from the static `WorldState` into transient falling bodies. The current gravity-affected set is `sand`, `red_sand`, and `gravel`. Once unsupported, these blocks leave the static world, advance on a Minecraft-like falling-block tick, and are rendered continuously between ticks through falling-block render samples. This design keeps the authoritative world map discrete while permitting the renderer to display motion that is smoother than a cell-by-cell mesh teleport."),
      paragraph("Landing is evaluated against the same implemented support semantics used elsewhere in the simulation. Lower stairs, fences, fence gates, and walls can serve as valid resting supports for a full falling block. A lower slab collision destroys the falling block and emits the same break-particle path used by ordinary manual block breaking. Landed gravity blocks also preserve player-overlap exemptions where the domain rule permits them, which keeps gravity settlement, collision resolution, and persisted reload behavior consistent."),
      paragraph("Break particles are sampled from active render boxes, not from an unconditional full-cube lattice. This is essential for slabs, stairs, fences, fence gates, and walls, because those families contain thin or partial members whose visible volume does not occupy the full unit cube. Stochastic volume sampling over the actual render boxes prevents thin members from producing visually uniform full-cube fragment rows, while persistent particle preferences allow the spawn rate and speed scale to be adjusted without changing block-state geometry."),
      code_block("gravity and particle classes/functions:\n  GravitySystem\n  GravityStepResult\n  GravityBrokenBlock\n  FallingBlockRenderSample\n  break_particle_samples_for_block()\n  build_break_particle_instances()\n  render_boxes_for_block()\n\ncurrent gravity-affected blocks:\n  sand\n  red_sand\n  gravel\n\nbreak-particle runtime controls:\n  block_break_particle_spawn_rate default: 1.0\n  block_break_particle_spawn_rate range: 0.0..2.0\n  block_break_particle_speed_scale default: 1.0\n  block_break_particle_speed_scale range: 0.1..3.0"),
    ),
  ),
  AboutSection(
    title="Player camera, HUD, skin, crosshair, and runtime preferences",
    blocks=(
      paragraph("Camera state is persisted through runtime preferences. The camera cycle follows the Minecraft-style order `First Person -> Third Person Back -> Third Person Front -> First Person`, with `F5` as the default keybind and an explicit camera selection available from video settings. Third-person placement is collision-constrained against block collision volumes so that the camera retracts before penetrating nearby geometry. Gameplay crosshair rendering is suppressed outside first person, and gameplay HUD visibility is controlled by `F1` and by the corresponding settings state."),
      paragraph("The player visual path separates simulation body state from rendered presentation state. The player’s simulation position, velocity, yaw, pitch, health, crouch-eye offset, ground state, and flight state are persisted through `PersistedPlayer`, while first-person arm geometry, third-person player model pose, held-block geometry, held Othello control item pose, hurt tint, swing animation, name-tag projection, and shadow-caster alignment are built by presentation visual modules and renderer passes. Modern imported skins use a `64x64` texture path and are persisted as `state/player_skin.png`, while reset restores the Alex default."),
      paragraph("The settings system exposes a persistent `16x16` crosshair editor, cloud controls, shadow controls, movement parameters, player-name storage, player skin state, camera perspective, view bobbing, camera shake, arm-rotation bounds, arm-swing duration, animated texture state, fullscreen preference, window geometry, keybinds, and audio category volumes. `AudioPreferences` normalizes master, ambient, block, and player volumes into the closed interval `[0, 1]`, and effective category gain is computed by multiplying the master gain by the category-specific gain."),
      code_block("camera constants:\n  first_person\n  third_person_back\n  third_person_front\n  cycle order: first_person -> third_person_back -> third_person_front -> first_person\n  default FOV: 80.0 degrees\n  mouse sensitivity: 0.09 degrees per pixel\n\ncrosshair:\n  grid size: 16x16\n  modes: default, custom\n\nskin:\n  modern skin texture: 64x64\n  persisted custom skin: state/player_skin.png\n  default skin kind: Alex\n\nHUD and controls:\n  gameplay HUD toggle: F1\n  debug HUD toggle: F3\n  camera cycle: F5\n  in-world name tag: third-person HUD path\n\naudio preferences:\n  categories: master, ambient, block, player\n  normalized volume interval: 0.0..1.0\n  effective non-master category gain: master * category"),
    ),
  ),
  AboutSection(
    title="AI-player runtime and route planning",
    blocks=(
      paragraph("The creative inventory exposes a searchable `AI` special item. Right-clicking a valid placement cell with that item spawns one standby AI actor at the target cell. The spawned actor is configured through an application-modal per-instance settings window that offers `Standby`, `Route Patrol`, and `Free Roam / PVP` modes, `Aggressive` and `Peaceful` personalities, a per-instance `Allow block placement` switch, route style selection, and deletion of the selected actor. The actor therefore enters the same persistent play-space model as the local player and world edits, instead of being treated as a transient visual decoration."),
      paragraph("AI state is represented through `AiPlayerState` and serialized through `PersistedAiPlayer`. The saved fields include actor id, mode, personality, block-placement permission, held item id, position, velocity, yaw, pitch, health, maximum health, ground state, flight state, route points, route closure, route execution state, route style, and route target index. Runtime behavior is divided across modules for idle behavior, wandering, route following, navigation, parkour, placement, avoidance, stuck detection, recovery, combat, spawning, serialization, manager coordination, and worker-backed route planning."),
      paragraph("Route authoring temporarily switches the active hotbar to a route-edit branch whose leftmost slot contains the check item, whose second slot contains the eraser item, and whose rightmost slot contains the cancel item. Left-clicking top faces records route points, the eraser focuses and deletes points under the crosshair, and the viewport renders draft and committed route lines as world-space line strips. Closed routes form loops; open routes traverse to the terminal point and then return to the first point. Flexible routing snapshots a bounded world window around the patrol region, computes support-cell paths on a background worker, accepts only complete routes that reach the authored patrol point, freezes when no complete route exists, and suspends route planning during active melee pursuit."),
      code_block("AI state and persistence:\n  AiPlayerState\n  AiRoutePoint\n  PersistedAiPlayer\n  AiPlayerManager\n\nAI modes:\n  Standby\n  Route Patrol\n  Free Roam / PVP\n\nAI personalities:\n  Aggressive\n  Peaceful\n\nroute styles:\n  Strict\n  Flexible\n\nroute-edit hotbar:\n  slot 1: check item\n  slot 2: eraser item\n  slot 9: cancel item\n\ncombat:\n  aggressive melee reach against player: 3 blocks\n  default AI health: 20.0\n\nAI runtime modules:\n  idle.py\n  wander.py\n  route.py\n  navigation.py\n  parkour.py\n  placement.py\n  avoidance.py\n  stuck.py\n  recovery.py\n  combat.py\n  spawning.py\n  serialization.py\n  manager.py\n  worker.py"),
    ),
  ),
  AboutSection(
    title="Othello play space and game-state semantics",
    blocks=(
      paragraph("`Play Othello (Reversi)` is a second persistent application mode hosted inside the same desktop shell. It disables ordinary block placement, block breaking, and the block inventory overlay. Its hotbar is reserved for control items: slot `1` contains `Start`, and slot `9` contains `Settings`. Selecting either item equips a dedicated enlarged control icon, which is rendered in first person, third person, and shadow-caster contexts so that the active control remains legible before use."),
      paragraph("The Othello board is an `8 x 8` board with `64` squares. The pristine persisted state renders the standard initial `2 x 2` center discs before the first match starts. Disc placement is performed by aiming at the board and pressing the left mouse button on a legal square. Hovering reports algebraic square names from `a1` through `h8`. The Othello HUD follows the panel style used by the `F3` debug HUD, hides whenever the ordinary debug HUD is shown or gameplay HUD rendering is disabled through `F1`, and otherwise reports turn, best move, principal line, player-versus-AI evaluation, and an evaluation graph derived from the current search trace."),
      paragraph("Match settings include AI strength, time control, disc-animation mode, player order, sacrifice level, worker count, hash level, and opening-book learning limits. The difficulty menu exposes `Weak`, `Medium`, `Strong`, `Insane`, and `Insane+`. The time-control menu exposes timer-off mode, per-move limits of `5`, `10`, and `30` seconds, and per-side limits of `1`, `3`, `5`, `10`, and `20` minutes. The default configuration remains `Medium`, `20 minutes per side`, `Animation off`, and player moves first. Match clocks pause while the pause menu or detached Othello settings window is open."),
      code_block("Othello board:\n  board size: 8x8\n  square count: 64\n  initial center discs: 2x2\n  algebraic names: a1..h8\n\nhotbar:\n  slot 1: Start\n  slot 9: Settings\n\nOthello classes and functions:\n  OthelloGameState\n  OthelloSettings\n  create_initial_board()\n  counts_for_board()\n  captures_for_move()\n  find_legal_moves()\n  has_any_legal_move()\n  apply_move()\n  winner_for_board()\n  square_index_to_name()\n  world_xz_to_square_index()\n  raycast_board_square()\n\nAI difficulty values:\n  Weak\n  Medium\n  Strong\n  Insane\n  Insane+\n\ntime controls:\n  Timer off\n  1 move 5 seconds\n  1 move 10 seconds\n  1 move 30 seconds\n  1 minute per side\n  3 minutes per side\n  5 minutes per side\n  10 minutes per side\n  20 minutes per side"),
    ),
  ),
  AboutSection(
    title="Othello search and opening-book learning",
    blocks=(
      paragraph("The Othello engine is divided into rule evaluation, board representation, bitboard operations, evaluation profiles, move ordering, search, transposition, worker execution, insane-tier selection, opening-book lookup, and learning. `Insane` uses the cached bitboard-search engine without enforced opening-book selection, while `Insane+` consults the bundled and user-extended opening book before falling through to the same search core. This means the higher tier is a storage-augmented search mode rather than a separate game-rule implementation."),
      paragraph("Opening-book learning is bounded by explicit numeric parameters. Learning depth admits `0..60`, with default `55`. Per-move error, cumulative error, and leaf-error bounds each admit `0..24`, with defaults `22`, `19`, and `20`. Starting a learning run resets active match state before learning begins, exposes cancellable progress, mirrors progress inside both the detached settings window and in-world Othello title HUD, temporarily projects the currently explored learning position onto the rendered board, and preserves partial progress on cancellation by writing user-generated book lines to `state/othello_opening_book.json`. The compiled lookup cache is stored under `cache/othello_opening_book_cache.json`."),
      paragraph("Book storage is symmetry-aware at the position level through canonicalized board transforms, so rotated and reflected equivalents are treated as the same opening-book position for lookup and learning-state pruning. This is an important algorithmic distinction because it reduces duplicate book states without changing Othello legality. Import and export operate on the user opening-book file path through application persistence hooks, so the simulation book logic can remain independent of the app-managed data-root policy."),
      code_block("Othello engine modules:\n  bitboards.py\n  classic.py\n  evaluation_profile.py\n  evaluation.py\n  insane.py\n  ordering.py\n  search.py\n  transposition.py\n  worker.py\n  books/opening.py\n  books/learning.py\n\nopening-book learning bounds:\n  depth range: 0..60\n  default depth: 55\n  per-move error range: 0..24\n  default per-move error: 22\n  cumulative error range: 0..24\n  default cumulative error: 19\n  leaf error range: 0..24\n  default leaf error: 20\n\nbook storage:\n  user extension: state/othello_opening_book.json\n  compiled cache: cache/othello_opening_book_cache.json\n\nbook properties:\n  symmetry-aware position canonicalization\n  cancellable learning progress\n  partial progress preservation on cancellation\n  import and export support"),
    ),
  ),
  AboutSection(
    title="Renderer contract and render snapshot boundary",
    blocks=(
      paragraph("Rendering is mediated through renderer contracts rather than direct widget access to backend internals. `BackendRendererApi` defines backend initialization, destruction, renderer information reporting, shadow information reporting, payload validation reporting, frame metrics, runtime-state application, cloud-motion pause state, texture-animation pause state, atlas UV lookup, world-build tools, block display-name resolution, chunk eviction, selection targeting, chunk submission, frame rendering, player-skin image updates, and player-preview rendering. This API permits the application shell, pause preview, settings surfaces, and viewport to address renderer behavior without knowing whether the active backend is OpenGL or wgpu."),
      paragraph("The render-snapshot boundary is equally important. Simulation and application state are composed into DTOs and render snapshots before being handed to presentation rendering. The renderer receives camera state, world chunks, falling-block samples, break-particle samples, player model state, AI player render state, held item state, Othello scene state, selection state, cloud and sun parameters, shadow parameters, HUD data, and texture-state changes as explicit input. This prevents the renderer from becoming the owner of domain rules while still letting it optimize upload, pass ordering, shader program use, and backend resources."),
      paragraph("The term backend parity has a precise meaning in Ludoxel. It does not require the OpenGL and wgpu implementations to use identical graphics APIs, identical shader compilation paths, identical buffer types, or identical surface creation. It requires a block state, UV rectangle, player skin region, selected face, shadow-caster transform, falling-block sample, Othello control item, and route overlay input to produce the same application-level visual meaning across backend families. Backend-specific divergence is therefore allowed in implementation mechanics, but not in the semantics of the rendered scene."),
      code_block("renderer contract classes:\n  BackendRendererApi\n  BackendRendererBackend\n  BackendRendererConfig\n  BackendRendererResources\n  BackendRendererRuntimeState\n  BackendRendererFrameMetrics\n  BackendPassFrameMetrics\n  BackendUploadTracker\n  RenderSnapshotDTO\n\nBackendRendererApi method surface:\n  initialize()\n  destroy()\n  gl_info()\n  shadow_info()\n  payload_validation_report()\n  frame_metrics()\n  apply_runtime_state()\n  set_cloud_motion_paused()\n  set_texture_animation_paused()\n  atlas_uv_face()\n  world_build_tools()\n  block_display_name()\n  evict_chunks()\n  clear_selection()\n  set_selection_target()\n  submit_chunk()\n  render()\n  set_player_skin_image()\n  render_player_preview_frame()\n\nrenderer semantic inputs:\n  chunk payloads\n  falling-block samples\n  break-particle samples\n  player model state\n  AI player render state\n  skin texture state\n  Othello scene state\n  selection state\n  cloud and sun parameters\n  shadow parameters"),
    ),
  ),
  AboutSection(
    title="OpenGL backend and GLSL resource model",
    blocks=(
      paragraph("The Windows renderer path uses PyOpenGL and the OpenGL backend under `presentation.rendering.backends.opengl`. It includes resource wrappers for shader programs, mesh buffers, colored mesh buffers, storage buffers, texture atlases, image textures, state guards, buffer upload, and array views. Higher-level rendering is decomposed into passes for world faces, shadow maps, player models, first-person arms, held blocks, falling blocks, block-break particles, clouds, selection outlines, the sun, special items, textured faces, and Othello rendering. This pass structure makes the frame pipeline explicit and allows individual render concerns to carry their own metrics and resources."),
      paragraph("The OpenGL surface configuration requests an OpenGL `4.3` core-profile style contract, a `24`-bit depth buffer, an `8`-bit stencil buffer, double buffering, zero multisample samples, and a swap interval derived from the v-sync preference. The shader root contains world, no-shadow world, shadow, player-model, no-shadow player-model, first-person face, cloud, sun, selection-line, Othello, Othello shadow, compute-payload, and shared face-instance shader resources. The presence of `chunk_face_payload.comp` is significant because the Windows OpenGL path can use a GLSL compute-shader style payload route that the macOS wgpu path is not required to compile or link."),
      paragraph("OpenGL-specific capability must be described narrowly. The project does not treat raw `gl_VertexID`, shader storage buffers, compute shaders, or indirect draw commands as portable assumptions for all platforms. `shader:check` validates the package shader roots and keeps obvious cross-profile hazards out of source. This is a necessary safeguard because macOS uses the wgpu backend through a Qt rendercanvas surface, while the Windows renderer retains the existing OpenGL implementation until backend migration is explicitly verified on Windows hardware."),
      code_block("OpenGL backend modules:\n  compute/chunk_payload.py\n  gl/array_view.py\n  gl/buffer_upload.py\n  gl/colored_mesh_buffer.py\n  gl/instanced_mesh_common.py\n  gl/mesh_buffer.py\n  gl/shader_program.py\n  gl/state_guard.py\n  gl/storage_buffer.py\n  passes/aggregated_face_batch.py\n  passes/block_break_particle.py\n  passes/cloud.py\n  passes/falling_block.py\n  passes/first_person_arm.py\n  passes/held_block.py\n  passes/player_model.py\n  passes/selection.py\n  passes/shadow_map.py\n  passes/special_item.py\n  passes/sun.py\n  passes/textured_face.py\n  passes/world.py\n  othello/render_pass.py\n  pipelines/frame.py\n  resources/image_texture.py\n  resources/texture_atlas.py\n  runtime/renderer.py\n\nOpenGL surface parameters:\n  version: 4.3\n  depth buffer: 24 bits\n  stencil buffer: 8 bits\n  samples: 0\n  double buffer: true\n  swap interval: 1 when vsync_on else 0\n\nOpenGL shader files:\n  chunk_face_payload.comp\n  cloud_box.frag\n  cloud_box.vert\n  first_person_face.frag\n  first_person_face.vert\n  othello_shadow.vert\n  othello.frag\n  othello.vert\n  player_model_no_shadow.frag\n  player_model_shadow.vert\n  player_model.frag\n  player_model.vert\n  selection_line.frag\n  selection_line.vert\n  shadow.frag\n  shadow.vert\n  sun.frag\n  sun.vert\n  world_no_shadow.frag\n  world.frag\n  world.vert\n  common/face_instance.glsl"),
    ),
  ),
  AboutSection(
    title="wgpu backend and macOS renderer path",
    blocks=(
      paragraph("The macOS renderer path is placed under `presentation.rendering.backends.wgpu` and is organized into chunk meshes, pipeline factory functions, runtime backend state, runtime resources, surface configuration, texture atlas handling, and shader sources. `configure_wgpu_canvas()` is the surface-level connection point between the Qt-hosted rendercanvas object and the wgpu backend. In external technical terms, wgpu is a WebGPU-oriented native graphics abstraction that can run on Metal, and rendercanvas supplies a canvas API capable of being hosted by Qt; in Ludoxel, those properties are used to avoid depending on Apple’s legacy OpenGL path for macOS rendering."),
      paragraph("The wgpu backend does not have to reproduce OpenGL mechanics. It has to reproduce renderer semantics. The same block-state-derived face, atlas UV rectangle, player skin region, first-person arm pose, third-person player pose, held block transform, Othello control item transform, falling-block sample, break-particle sample, selection outline, cloud state, and shadow-related scene meaning must remain coherent even when buffer construction, pipeline creation, surface presentation, and shader translation differ from the Windows OpenGL path."),
      paragraph("The wgpu shader source tree mirrors the OpenGL shader naming surface, including `world`, `shadow`, `player_model`, `first_person_face`, `cloud_box`, `selection_line`, `sun`, `othello`, and shared `face_instance` sources. However, the macOS path is described in the old README as not compiling or linking `chunk_face_payload.comp`, and as not requiring GLSL 4.30 compute shaders, shader storage buffers, or `glMultiDrawArraysIndirect`. That distinction is essential because the shader directory may contain mirrored files as source resources while backend runtime support remains explicitly platform-specific."),
      code_block("wgpu backend modules:\n  meshes/chunk.py\n  pipelines/factory.py\n  runtime/backend.py\n  runtime/resources.py\n  runtime/surface.py\n  textures/atlas.py\n\nwgpu pipeline factory functions:\n  create_world_pipeline()\n  create_world_wireframe_pipeline()\n  create_world_shadowed_pipeline()\n  create_shadow_depth_pipeline()\n  create_transform_shadow_pipeline()\n  create_sun_pipeline()\n  create_cloud_pipeline()\n  create_cloud_wireframe_pipeline()\n  create_selection_pipeline()\n  create_othello_pipeline()\n  create_othello_shadow_pipeline()\n\nmacOS renderer stack:\n  PyQt6 desktop window\n  rendercanvas Qt surface\n  wgpu Python package\n  wgpu-native\n  Metal backend\n\nmacOS renderer exclusions:\n  no required OpenGL 4.3 context\n  no required GLSL 4.30 compute-shader path\n  no required shader storage buffer path\n  no required glMultiDrawArraysIndirect path"),
    ),
  ),
  AboutSection(
    title="Input ownership, modal states, and macOS capture behavior",
    blocks=(
      paragraph("Input handling is owned by presentation input modules and viewport lifecycle code. Qt key events, mouse events, gameplay input state, macOS keyboard interception, and macOS cursor recentering are separated into `game_input.py`, `qt.py`, `macos_guard.py`, and `macos_cursor.py`. This distinction matters because captured gameplay, inventory, pause, death overlay, detached settings, detached Othello settings, notice dialogs, application deactivation, and shell reactivation each impose different rules on whether input should advance simulation, steer the camera, update a preview, operate UI controls, or be released to the operating system."),
      paragraph("Mouse-look capture includes a resynchronization phase after capture is re-enabled. During that phase the system cursor is repeatedly recentered, keyboard movement continues to flow, camera delta is forced to zero, and ordinary mouse-look sampling resumes only after the cursor remains at the viewport center across successive polls. On macOS, gameplay capture separates keyboard interception from mouse confinement: the keyboard path installs the CoreGraphics event-tap guard, while the mouse path recenters the system cursor through a CoreGraphics cursor-warp helper before falling back to Qt cursor positioning. The `.app` bundle declares the keyboard guard through `NSInputMonitoringUsageDescription`."),
      paragraph("Renderer motion is suspended for true application deactivation and for pause, death, inventory, Othello-settings, and short-lived notice-dialog states. The detached general settings window remains live so visual settings can be inspected against the world in real time. When the shell becomes active again, the viewport explicitly re-arms the next world upload and selection refresh so that returning from pause or inventory does not depend on stale render cadence. This makes input suspension and renderer refresh part of one state machine rather than two unrelated UI conveniences."),
      code_block("input modules:\n  presentation/interface/input/game_input.py\n  presentation/interface/input/qt.py\n  presentation/interface/input/macos_guard.py\n  presentation/interface/input/macos_cursor.py\n\nviewport modules:\n  presentation/interface/viewport/widgets/gl.py\n  presentation/interface/viewport/widgets/renderer.py\n  presentation/interface/viewport/lifecycle/mixin.py\n  presentation/interface/viewport/lifecycle/state.py\n  presentation/interface/viewport/render_loop/frame_sync.py\n  presentation/interface/viewport/render_loop/loop.py\n  presentation/interface/viewport/overlays/controller.py\n  presentation/interface/viewport/selection/state.py\n\nmacOS bundle key:\n  NSInputMonitoringUsageDescription\n\ncapture behavior:\n  captured gameplay owns mouse-look\n  modal UI suspends simulation input\n  application deactivation releases capture\n  capture re-enable enters recenter-and-zero-delta resynchronization"),
    ),
  ),
  AboutSection(
    title="Settings surfaces and About-page documentation model",
    blocks=(
      paragraph("The settings system is an application-modal surface that exposes visual, player, controls, audio, Othello, cloud-flow, and About content without forcing the user to leave the running world. The detached settings shell temporarily exits fullscreen when necessary and reapplies the stored fullscreen preference after the dialog closes. This preserves access to ordinary desktop controls while maintaining fullscreen as a persisted preference instead of an irreversible display state."),
      paragraph("The About page is implemented through `AboutSection`, `AboutBlock`, `paragraph()`, `code_block()`, and `render_about_sections()`. This means the project overview is not a README excerpt pasted into a widget; it is structured UI content whose paragraphs and code-like blocks are rendered by the application’s settings/about renderer and widgets. The content must therefore satisfy two requirements at once: it must be readable inside a desktop settings page, and it must accurately describe the class boundaries, function ownership, parameter values, renderer constraints, persistence files, development commands, and distribution policy present in the codebase."),
      paragraph("The creator-facing text is also separated from project-overview text. `ABOUT_PROFILE_BIO_TEXT`, `ABOUT_WORK_TEXT`, `ABOUT_ACADEMIC_DIRECTION_TEXT`, and `ABOUT_ETYMOLOGY_PARAGRAPHS` describe creator identity, academic direction, work description, and name origin. `ABOUT_PROJECT_OVERVIEW_SECTIONS` must describe the project itself. It should therefore include engineering, academic, development, packaging, legal, and renderer facts where those facts define the actual software, while avoiding promotional prose that cannot be traced to source layout, configuration, commands, or runtime behavior."),
      code_block("About content constants:\n  ABOUT_GITHUB_URL\n  ABOUT_CREATOR_DISPLAY_NAME\n  ABOUT_CREATOR_HANDLE\n  ABOUT_CREATOR_ROLE\n  ABOUT_CREATOR_AGE\n  ABOUT_CREATOR_GENDER\n  ABOUT_PROFILE_BIO_TEXT\n  ABOUT_WORK_TEXT\n  ABOUT_ACADEMIC_DIRECTION_TEXT\n  ABOUT_ETYMOLOGY_PARAGRAPHS\n  ABOUT_PROJECT_OVERVIEW_SECTIONS\n\nAbout structures:\n  @dataclass(frozen=True) AboutBlock\n  @dataclass(frozen=True) AboutSection\n\nAbout helper functions:\n  paragraph(text: str) -> AboutBlock\n  code_block(text: str) -> AboutBlock\n  render_about_sections(layout, sections)\n  about_card()\n  about_text()\n  about_code_block()\n  about_meta_row()\n  about_pill()"),
    ),
  ),
  AboutSection(
    title="Development workflow and repository command surface",
    blocks=(
      paragraph("The development workflow is part of Ludoxel’s technical identity because source-tree execution, editable installation, native rebuilds, shader validation, resource validation, package-data validation, documentation validation, license validation, and desktop packaging are all defined through repository commands. The README identifies `python -m ludoxel` as the canonical source-tree startup route, `python -m pip install -e .` as the ordinary editable install, and `npm run check` as the full local verification surface. Python source uses a two-space indentation policy enforced through the repository formatting and linting tools."),
      paragraph("The package metadata declares `PyQt6 >=6.6,<7`, `numpy >=1.26,<3`, `PyOpenGL >=3.1,<4` on Windows, and `wgpu >=0.31,<0.32` plus `rendercanvas >=2.6,<3` on macOS. Development extras include `build`, `Cython`, `PyInstaller`, `setuptools`, `wheel`, and `ruff`. The ordinary editable install is intentionally separated from native extension compilation, so Cython execution is not an implicit side effect of every metadata evaluation or source-tree install. The explicit native path is entered through `npm run build:native` and verified through `npm run build:native:check`."),
      paragraph("The repository command surface is rooted in `package.json` and `tools/`, with no supported root-level `scripts/` directory. The active tool directories include help commands, project checks, native extension builds, desktop app builds, cleanup, directory export, Python formatting, web formatting, and audio conversion. This command surface is part of the project specification because it determines how future changes are verified, how resources are checked, how shaders are validated, how legal material is enforced, and how desktop bundles are produced."),
      code_block("source-tree setup:\n  python -m pip install -e .\n  python -m ludoxel\n\ndevelopment setup:\n  python -m pip install -e \".[dev]\"\n  npm install\n\nverification commands:\n  npm run help\n  npm run check\n  npm run ci\n  npm run format\n  npm run format:check\n  npm run lint\n  npm run package:check\n  npm run docs:check\n  npm run license:check\n  npm run resources:check\n  npm run shader:check\n  npm run tools:export\n  npm run tools:test\n\nactive tool directories:\n  tools/help_commands\n  tools/check_project\n  tools/build_native_extensions\n  tools/build_desktop_app\n  tools/clean_build_artifacts\n  tools/export_directory_markdown\n  tools/format_python_source\n  tools/format_web_source\n  tools/convert_audio_assets\n\nRuff policy:\n  line-length: 200\n  indent-width: 2\n  target-version: py313\n  quote-style: double\n  skip-magic-trailing-comma: true"),
    ),
  ),
  AboutSection(
    title="Native acceleration boundary",
    blocks=(
      paragraph("The native build is deliberately narrow. Only `ludoxel.foundations.mathematics.geometry.ray_aabb`, `ludoxel.foundations.mathematics.voxels.dda`, and `ludoxel.foundations.mathematics.linear.view_angles` are compiled in place. These targets are appropriate because they are dominated by scalar arithmetic, geometric branching, voxel traversal, and dense view-angle computations. Broader orchestration layers remain in Python because their runtime behavior is governed primarily by object traffic, dictionary access, callback dispatch, heterogeneous containers, UI state, session management, and renderer-resource ownership, which do not automatically benefit from opaque extension-module compilation."),
      paragraph("The explicit native build path is also a recovery and verification mechanism. `npm run build:native` enters `tools/build_native_extensions`, generates the build script, drives the native extension build, and writes in-place binary modules. `npm run build:native:check` verifies that the interpreter resolves those hot-path imports to compiled binaries rather than Python fallback sources. Windows builds resolve to `.pyd` files, while macOS builds resolve to `.so` files. This distinction matters because extension modules are interpreter-version-specific, and the repository’s packaging and development instructions keep that specificity visible."),
      paragraph("The editable install and native build separation protects ordinary development. `pyproject.toml` describes package metadata, dependency declarations, package data, dynamic version resolution, and console script entry points. Native compilation remains an explicit optimization step. Desktop Windows packaging can invoke the narrow native rebuild automatically unless skipped, while source-tree development can choose the Python fallback path when native performance recovery is not required."),
      code_block("native extension targets:\n  ludoxel.foundations.mathematics.geometry.ray_aabb\n  ludoxel.foundations.mathematics.voxels.dda\n  ludoxel.foundations.mathematics.linear.view_angles\n\nnative commands:\n  npm run build:native\n  npm run build:native:check\n\nnative output forms:\n  Windows: .pyd\n  macOS: .so\n\nordinary editable install:\n  python -m pip install -e .\n\neditable install with development extras:\n  python -m pip install -e \".[dev]\""),
    ),
  ),
  AboutSection(
    title="Desktop packaging and resource distribution",
    blocks=(
      paragraph("Desktop packaging is part of the application specification because Ludoxel contains platform-dependent renderer paths, package resources, fonts, legal material, native-extension recovery, runtime data-root policy, and platform-specific input behavior. The Windows path uses `npm run build:windows` as the primary executable build command. It invokes PyInstaller in one-file mode from `src/ludoxel/__main__.py`, collects package data under `src/ludoxel`, bundles repository-level resources, publishes `dist/windows/Ludoxel.exe`, and emits `LICENSE`, `NOTICE`, and `third-party/` beside the executable. The Windows builder also keeps the application’s runtime writes under the app-managed data root instead of creating repository-level or executable-adjacent `configs` as the normal persistence path."),
      paragraph("The macOS path uses `npm run build:macos`, `npm run build:macos:check`, and `npm run build:macos -- --status` as the local app-bundle verification surface. It builds a PyInstaller `.app`, preserves the bundled Python framework symlink layout, collects the Python `wgpu` and `rendercanvas` packages, preserves bundled assets and fonts, records the gameplay input monitoring usage string in `Info.plist`, re-signs the bundle after that patch, verifies bundled font presence, and preserves legal material. Codesigning and notarization remain separate release steps."),
      paragraph("Resource distribution distinguishes immutable bundled resources from runtime user data. Theme resources live under `presentation/interface/theme`, OpenGL shader resources under `presentation/rendering/backends/opengl/shaders`, wgpu shader sources under `presentation/rendering/backends/wgpu/shaders/sources`, and Othello bundled resources under `simulation/spaces/othello/resources`. Desktop builds must bundle fonts under `assets/fonts`, and runtime startup registers bundled fonts rather than relying on a platform system-font fallback. This is a user-visible correctness issue because missing fonts alter the actual application surface even when source-tree execution appears otherwise functional."),
      code_block("Windows packaging:\n  npm run build:windows\n  frozen entry script: src/ludoxel/__main__.py\n  published executable: dist/windows/Ludoxel.exe\n  Windows icon candidate: assets/ui/app_icon.ico\n  companion legal material: LICENSE, NOTICE, third-party/\n\nmacOS packaging:\n  npm run build:macos\n  npm run build:macos:check\n  npm run build:macos -- --status\n  app bundle: dist/macos/Ludoxel.app\n  renderer path: wgpu-native through rendercanvas and Qt\n  input-monitoring plist key: NSInputMonitoringUsageDescription\n  release steps outside local build: codesigning and notarization\n\npackage resource roots:\n  presentation/interface/theme\n  presentation/rendering/backends/opengl/shaders\n  presentation/rendering/backends/wgpu/shaders/sources\n  simulation/spaces/othello/resources\n\nruntime-writable data:\n  app-managed data root\n  state/\n  cache/"),
    ),
  ),
  AboutSection(
    title="Legal material, third-party resources, and governance boundary",
    blocks=(
      paragraph("Ludoxel Original Materials are governed by `LicenseRef-All-Rights-Reserved` under the Ludoxel Independent License in `LICENSE`. The repository is not open source and is not licensed under Apache-2.0, MIT, BSD, GPL, AGPL, LGPL, MPL, or another open-source license. This legal status is not a decorative README note; it directly affects repository metadata, NOTICE text, distribution packaging, third-party material separation, GitHub policy, contribution assumptions, and how desktop builds must carry legal material."),
      paragraph("`NOTICE` records the relationship between Ludoxel Original Materials, third-party materials, provenance-sensitive local assets, runtime user data, and distribution legal material. Third-party license texts are kept under `third-party/`. Kaisei Opti is documented under `third-party/kaisei-opti/` with SIL Open Font License material. Local Minecraft-named assets and fonts under `assets/` are not to be represented as original Ludoxel assets, and their redistribution rights are not established by the repository. This distinction prevents packaged resources, local convenience files, and original project materials from being conflated."),
      paragraph("The governance boundary also appears in `.github/` policy. External contributions are not accepted, issue forms are limited, security reporting is separated, Dependabot is scoped, and CI uses the same npm entrypoint used locally. The project’s legal, packaging, verification, and governance surfaces therefore operate as one system: source code may be visible for review, while reuse, redistribution, derivative construction, and contribution intake remain restricted by the project’s license and policy documents."),
      code_block("license identifier:\n  LicenseRef-All-Rights-Reserved\n\nprincipal legal files:\n  LICENSE\n  NOTICE\n  third-party/\n\nthird-party font record:\n  third-party/kaisei-opti/NOTICE.txt\n  third-party/kaisei-opti/LICENSE.txt\n\nmaterials requiring provenance caution:\n  assets/minecraft/\n  Minecraft-named local fonts under assets/fonts/\n\nGitHub policy boundary:\n  external contributions not accepted\n  issue forms limited\n  security reporting separated\n  Dependabot scoped\n  CI uses the local npm verification entrypoint"),
    ),
  ),
)
