# SPDX-FileCopyrightText: 2026 Kento Konishi
# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from .ai import choose_ai_move
from .board import BOARD_SIZE, OTHELLO_BOARD_BLOCK_Y, OTHELLO_BOARD_DARK_BLOCK_ID, OTHELLO_BOARD_LIGHT_BLOCK_ID, OTHELLO_BOARD_MIN_X, OTHELLO_BOARD_MIN_Z, OTHELLO_BOARD_SURFACE_Y, ensure_othello_board_layout, is_othello_board_footprint, othello_board_block_updates, raycast_board_square, square_center, square_index_to_row_col, world_xz_to_square_index
from .rules import apply_move, counts_for_board, create_initial_board, find_legal_moves, has_any_legal_move, index_to_row_col, other_side, row_col_to_index, winner_for_board
from .types import OTHELLO_ANIMATION_FAST, OTHELLO_ANIMATION_MODES, OTHELLO_ANIMATION_OFF, OTHELLO_ANIMATION_SLOW, OTHELLO_DIFFICULTY_INSANE, OTHELLO_DIFFICULTY_INSANE_PLUS, OTHELLO_DIFFICULTY_MEDIUM, OTHELLO_DIFFICULTY_STRONG, OTHELLO_DIFFICULTY_WEAK, OTHELLO_GAME_STATE_AI_TURN, OTHELLO_GAME_STATE_ANIMATING, OTHELLO_GAME_STATE_FINISHED, OTHELLO_GAME_STATE_IDLE, OTHELLO_GAME_STATE_PLAYER_TURN, OTHELLO_TIME_CONTROL_NONE, OTHELLO_TIME_CONTROL_OFF, OTHELLO_TIME_CONTROL_PER_MOVE_10S, OTHELLO_TIME_CONTROL_PER_MOVE_30S, OTHELLO_TIME_CONTROL_PER_MOVE_5S, OTHELLO_TIME_CONTROL_PER_SIDE_10M, OTHELLO_TIME_CONTROL_PER_SIDE_1M, OTHELLO_TIME_CONTROL_PER_SIDE_20M, OTHELLO_TIME_CONTROL_PER_SIDE_3M, OTHELLO_TIME_CONTROL_PER_SIDE_5M, OTHELLO_WINNER_DRAW, SIDE_BLACK, SIDE_EMPTY, SIDE_WHITE, OthelloAnimationState, OthelloGameState, OthelloSettings, animation_mode_display_name, difficulty_display_name, empty_othello_game_state, normalize_animation_mode, normalize_difficulty, normalize_game_status, normalize_player_side, normalize_side, normalize_time_control, time_control_display_name, time_control_is_per_move, time_control_limit_s

__all__ = ["BOARD_SIZE", "OTHELLO_ANIMATION_FAST", "OTHELLO_ANIMATION_MODES", "OTHELLO_ANIMATION_OFF", "OTHELLO_ANIMATION_SLOW", "OTHELLO_BOARD_BLOCK_Y", "OTHELLO_BOARD_DARK_BLOCK_ID", "OTHELLO_BOARD_LIGHT_BLOCK_ID", "OTHELLO_BOARD_MIN_X", "OTHELLO_BOARD_MIN_Z", "OTHELLO_BOARD_SURFACE_Y", "OTHELLO_DIFFICULTY_INSANE", "OTHELLO_DIFFICULTY_INSANE_PLUS", "OTHELLO_DIFFICULTY_MEDIUM", "OTHELLO_DIFFICULTY_STRONG", "OTHELLO_DIFFICULTY_WEAK", "OTHELLO_GAME_STATE_AI_TURN", "OTHELLO_GAME_STATE_ANIMATING", "OTHELLO_GAME_STATE_FINISHED", "OTHELLO_GAME_STATE_IDLE", "OTHELLO_GAME_STATE_PLAYER_TURN", "OTHELLO_TIME_CONTROL_NONE", "OTHELLO_TIME_CONTROL_OFF", "OTHELLO_TIME_CONTROL_PER_MOVE_10S", "OTHELLO_TIME_CONTROL_PER_MOVE_30S", "OTHELLO_TIME_CONTROL_PER_MOVE_5S", "OTHELLO_TIME_CONTROL_PER_SIDE_10M", "OTHELLO_TIME_CONTROL_PER_SIDE_1M", "OTHELLO_TIME_CONTROL_PER_SIDE_20M", "OTHELLO_TIME_CONTROL_PER_SIDE_3M", "OTHELLO_TIME_CONTROL_PER_SIDE_5M", "OTHELLO_WINNER_DRAW", "SIDE_BLACK", "SIDE_EMPTY", "SIDE_WHITE", "OthelloAnimationState", "OthelloGameState", "OthelloSettings", "animation_mode_display_name", "apply_move", "choose_ai_move", "counts_for_board", "create_initial_board", "difficulty_display_name", "empty_othello_game_state", "ensure_othello_board_layout", "find_legal_moves", "has_any_legal_move", "index_to_row_col", "is_othello_board_footprint", "normalize_animation_mode", "normalize_difficulty", "normalize_game_status", "normalize_player_side", "normalize_side", "normalize_time_control", "other_side", "othello_board_block_updates", "raycast_board_square", "row_col_to_index", "square_center", "square_index_to_row_col", "time_control_display_name", "time_control_is_per_move", "time_control_limit_s", "winner_for_board", "world_xz_to_square_index"]
