/*
 * SPDX-FileCopyrightText: 2026 Kento Konishi
 * SPDX-License-Identifier: LicenseRef-All-Rights-Reserved
 */
export const EXPORT_TARGETS = Object.freeze({
  root: Object.freeze({
    name: 'root',
    directory: '.',
    outputBaseName: 'root_export',
    description: 'repository root, excluding generated artifacts and local runtime data',
  }),
  src: Object.freeze({
    name: 'src',
    directory: 'src',
    outputBaseName: 'src_export',
    description: 'Ludoxel source tree',
  }),
  tools: Object.freeze({
    name: 'tools',
    directory: 'tools',
    outputBaseName: 'tools_export',
    description: 'repository tools',
  }),
  archive: Object.freeze({
    name: 'archive',
    directory: '.',
    outputBaseName: 'archive_export',
    description: 'repository archive-oriented export with strict generated exclusions',
  }),
});

export const DEFAULT_TARGET = 'root';

export const DEFAULT_EXCLUDED_DIRECTORY_NAMES = Object.freeze([
  '.git',
  '.artifacts',
  '.venv',
  '.venv_ludoxel',
  '__pycache__',
  '.pytest_cache',
  '.mypy_cache',
  '.ruff_cache',
  'node_modules',
  'dist',
  'build',
  'coverage',
]);

export const DEFAULT_EXCLUDED_RELATIVE_PREFIXES = Object.freeze(['tools/export_directory_markdown/output', 'tools/format_python_source/.cache']);

export const DEFAULT_BINARY_EXTENSIONS = Object.freeze([
  '.aac',
  '.aif',
  '.aiff',
  '.ani',
  '.apng',
  '.app',
  '.avif',
  '.avi',
  '.bin',
  '.bmp',
  '.bz2',
  '.class',
  '.cur',
  '.db',
  '.deb',
  '.dds',
  '.dll',
  '.dmg',
  '.doc',
  '.docx',
  '.dylib',
  '.eot',
  '.exe',
  '.flac',
  '.gif',
  '.gz',
  '.heic',
  '.heif',
  '.icns',
  '.ico',
  '.jar',
  '.jpeg',
  '.jpg',
  '.ktx',
  '.ktx2',
  '.m4a',
  '.m4v',
  '.mid',
  '.midi',
  '.mkv',
  '.mov',
  '.mp3',
  '.mp4',
  '.msi',
  '.npy',
  '.npz',
  '.ogg',
  '.opus',
  '.otf',
  '.pdf',
  '.pkl',
  '.png',
  '.ppt',
  '.pptx',
  '.pyd',
  '.rar',
  '.rpm',
  '.sqlite',
  '.so',
  '.svg',
  '.tar',
  '.tga',
  '.tif',
  '.tiff',
  '.ttc',
  '.ttf',
  '.wasm',
  '.wav',
  '.webm',
  '.webp',
  '.woff',
  '.woff2',
  '.xls',
  '.xlsx',
  '.xz',
  '.7z',
  '.zip',
  '.pyc',
]);
