name: "Ludoxel License Metrics"

"on":
  push:
    branches:
      - "main"
    paths-ignore:
      - "assets/branding/ludoxel-license.svg"
  schedule:
    - cron: "17 18 * * *"
  workflow_dispatch: {}

permissions:
  contents: "write"

jobs:
  generate:
    name: "Generate Ludoxel license metrics"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Generate license metrics"
        uses: "lowlighter/metrics@latest"
        with:
          filename: "assets/branding/ludoxel-license.svg"
          token: "${{ secrets.GITHUB_TOKEN }}"
          user: "${{ github.repository_owner }}"
          template: "repository"
          repo: "Ludoxel"
          config_timezone: "Asia/Tokyo"
          plugin_licenses: "yes"
          plugin_licenses_legal: "no"
          plugin_licenses_ratio: "yes"
